### ISSUE TITLE
Migrate error

### ISSUE THREAD

**Issue by 7wonders** [django-tastypie/django-tastypie#1005]
Getting this error when running migrate

Running migrations for tastypie:
 - Migrating forwards to 0002_add_apikey_index.
 > tastypie:0001_initial
TypeError: type() argument 1 must be string, not unicode

any ideas?

**Comment by posita** [comment]
FYI, see also <https://bugs.python.org/issue21720>.

**Comment by SeanHayes** [comment]
Closing in favor of pull request.

**Comment by benjaoming** [comment]
Any chance there will be a new release containing this fix since it still only lives in master...?

**Comment by SeanHayes** [comment]
@benjaoming New release is on PyPi.

**Comment by benjaoming** [comment]
Thanks @SeanHayes, much appreciated and congrats on another release!

**Comment by benjaoming** [comment]
For the record, if anyone is wondering, this was never merged nor released and thus tastypie 0.12.2, the final version with South support cannot migrate forwards.

Hopefully we've all moved beyond South :)
