### ISSUE TITLE
Custom User field not getting read from compat.py during ApiAuthentication

### ISSUE THREAD

**Issue by devangmundhra** [django-tastypie/django-tastypie#1009]
I have a Django project with a custom user field. When using ApiAuthentication for a modelresource, at
https://github.com/toastdriven/django-tastypie/blob/master/tastypie/authentication.py#L183

the User field is None causing the User.DoesNotExist exception. However, if instead of doing `from tastypie.compat import User` I actually put in the code from compat.py here, the custom user model and username_field are set fine.

**Comment by SeanHayes** [comment]
I think this has been fixed by another change.
