### ISSUE TITLE
support for generic relations

### ISSUE THREAD

**Issue by tiabas** [django-tastypie/django-tastypie#101]
I was wondering if there is an easy way to handle generic relationship for models that possess them. Right now, I'm using a hack by making a model resource for Django's builtin Contenttype  model and then subsequently  making queries that use app_label & object_id inorder to retrieve an object using tastypie. 

something like this:

from django.contrib.contenttypes.models import ContentType

class ContentTypeResource(ModelResource):
	class Meta:
		queryset = ContentType.objects.all()
		resource_name = 'contenttypes'
		fields = ['model']
		detail_allowed_methods = ['get',]
		list_allowed_methods = ['get']

**Comment by georgedorn** [comment]
Looks like this got added in #620.
