### ISSUE TITLE
Nested resource example in cookbook returns only one of many possible values

### ISSUE THREAD

**Issue by Borkason** [django-tastypie/django-tastypie#1031]
I followed the example of the cookbook for nested resources and it only returns one of many possible values.

**api.py**
https://dpaste.de/AndzG/

**models.py**
https://dpaste.de/brkcP/

**http://localhost:8000/api/customer/1/**
{"dishes": ["/api/dish/1/", "/api/dish/3/"], "id": 1, "resource_uri": "/api/customer/1/", "restaurants": ["/api/restaurant/1/"]}

**http://localhost:8000/api/customer/1/favourite_dishes/**
{"id": 1, "name": "Pizza Mozarella", "resource_uri": "/api/dish/1/"}

**Comment by rregue** [comment]
As a workaround I am implementing a custom build_filter on the child resource and then I set the self._meta.limit = qs.count() if the custom filter is found. 
This is not desirable at all, but is there any other quick fix to handle this and have the next and previous of the pagination work properly?
