### ISSUE TITLE
apply_authorization_limits deprecated but still listed in documentation

### ISSUE THREAD

**Issue by chrismeyersfsu** [django-tastypie/django-tastypie#1045]
Using apply_authorization_limits it recommended as a way to enforce per-user-resources. However, the method is deprecated.

http://django-tastypie.readthedocs.org/en/latest/cookbook.html#creating-per-user-resources

Consider linking to the Authorization example that accomplishes per-user-resource enforcement.

http://django-tastypie.readthedocs.org/en/latest/authorization.html#implementing-your-own-authorization

**Comment by prudnikov** [comment]
Totally agree with @honi comment regarding this issue. Any comments by core team on that?

**Comment by SeanHayes** [comment]
Closed by #1433
