### ISSUE TITLE
Proper json encoding

### ISSUE THREAD

**Issue by kmike** [django-tastypie/django-tastypie#105]
From the docs for django serializer: 

> If you're using UTF-8 (or any other non-ASCII encoding) data with the JSON serializer, you must pass ensure_ascii=False as a parameter to the serialize() call. Otherwise, the output won't be encoded correctly.

http://docs.djangoproject.com/en/dev/topics/serialization/#notes-for-specific-serialization-formats 

So I think serializers.Serializer.to_json (https://github.com/toastdriven/django-tastypie/blob/master/tastypie/serializers.py#L293) should pass 'ensure_ascii=False' to simplejson.dumps:

```
def to_json(self, data, options=None):        
    options = options or {}
    data = self.to_simple(data, options)
    return simplejson.dumps(data, cls=json.DjangoJSONEncoder,
                            sort_keys=True, ensure_ascii=False)
```

This change leads to easier to read and smaller utf8-encoded json responses for me (instead of \uxxxx-encoded strings).

I haven't tested this extensively and this is technically backwards-incompatible but I think the current behavior is worth changing.

**Comment by johndeng** [comment]
@kmike @toastdriven It's not a good idea to change the json.dumps default encoding behavior, the backwards-compatible is breakdown completely.
