### ISSUE TITLE
Authorization Methods Design Problem for Non-ORM Resources

### ISSUE THREAD

**Issue by tunix** [django-tastypie/django-tastypie#1086]
### Description

Authorization class method signatures are like the following:

```
def read_detail(self, object_list, bundle):
        """
        Returns either ``True`` if the user is allowed to read the object in
        question or throw ``Unauthorized`` if they are not.

        Returns ``True`` by default.
        """
        return True
```

The signature is perfectly fine for model backed resources but not very good for non-orm resources where there is no QuerySet impl. at all. Because of this, it's being hard to apply filtering before actual SQL execution (i.e.: filtering objects which belong to a specific user)

**Comment by SeanHayes** [comment]
You don't have to filter `object_list`, the object should be available on `bundle.obj`, you can just write some Python to determine if it can be read.
