### ISSUE TITLE
Setting custom JSON serializer for Resource affect also serialization of resource's schema document

### ISSUE THREAD

**Issue by Jokipii** [django-tastypie/django-tastypie#1095]
When I use  custom serializer CamelCaseJSONSerializer 
from http://django-tastypie.readthedocs.org/en/latest/cookbook.html#camelcase-json-serialization for resource. Example:

```python
class TagResource(ModelResource):
    class Meta:
        queryset = Tag.objects.all()
        resource_name = 'tag'
        serializer = CamelCaseJSONSerializer()
        default_format = 'application/json'
        list_allowed_methods = ['get', 'post']
        detail_allowed_methods = ['get', 'put', 'delete', 'patch']
```

Custom serializer is also affect on serialization of resource schema document. In example case /api/v1/tag/schema/ looks like:

```json
{
    "defaultLimit": 20,
    "fields": {
        "name": {
            "nullable": false,
            "default": "",
            "readonly": false,
            "helpText": "Unicode string data. Ex: \"Hello World\"",
            "blank": true,
            "unique": false,
            "type": "string"
        }
    },
    "defaultFormat": "application/json",
    "allowedListHttpMethods": [
        "get",
        "post"
    ],
    "allowedDetailHttpMethods": [
        "get",
        "put",
        "delete",
        "patch"
    ]
}
```

I think that setting custom JSON serializer shouldn't affect schema document, but only serialization of resource itself.

**Comment by SeanHayes** [comment]
I think most developers who care about camel casing would want it everywhere.

You could make your custom serializer define a separate camel cased JSON format with a custom mimetype, and use that custom mimetype when you want camel casing.
