### ISSUE TITLE
Interacting with API Documentation Needs Clarification

### ISSUE THREAD

**Issue by brianwc** [django-tastypie/django-tastypie#1101]
In the Interacting with the API page of the documentation, there's the part that says:

"Let's try filtering on the resource. Since we know we can filter on the user, we'll fetch all posts by the daniel user with:

curl http://localhost:8000/api/v1/entry/?user__username=daniel "

However, nothing that I see in the preceding examples would have told us to use "username" and so generalizing from this example to other situations is difficult because it is unclear what generates the format: "?something__somethingelse=query"
How does one know what to put in the __somethingelse spot?

**Comment by SeanHayes** [comment]
The format is the same one used by the Django ORM filtering.
