### ISSUE TITLE
Deleting a resource multiple times returns 404 instead of 410

### ISSUE THREAD

**Issue by devangmundhra** [django-tastypie/django-tastypie#1109]
The [documentation](http://django-tastypie.readthedocs.org/en/latest/interacting.html#deleting-a-single-resource) states that when a resource is deleted multiple times, the first successful return code will be `Accepted 204` and all consequent ones will return in `Gone 410`. 
However, when I try this, I get `Not found 404` instead of `410`.
```
HTTP/1.1 404 NOT FOUND
Date: Sat, 04 Jan 2014 05:45:57 GMT
Server: Apache/2.2.22 (Ubuntu)
Vary: Accept,Cookie,Accept-Encoding
Content-Length: 0
Connection: close
Content-Type: text/html; charset=utf-8
```
While both of them seem to be the correct response, I just wanted to confirm what is the standard to follow here.
I am trying to delete a resource using a mobile app and I need to parse the response code to see if I need to delete the resource from the local cache if the object has already been deleted from the server, or if there was actually some problem in deleting the resource on the server which needs to be looked into.

**Comment by SeanHayes** [comment]
Updated the docs, thanks!
