### ISSUE TITLE
How to validate unique together constraint?

### ISSUE THREAD

**Issue by johnnywell** [django-tastypie/django-tastypie#1119]
Excuse me for asking this question here, but I could not find solution and also got no answer on the mailing list.

I'm using Tastypie 0.9.16 and Django 1.3.1 for compatibility requirement in the project.

Restrito model has a unique_together = ('usuario', 'titulo'), and I have two resources, UserResource and RestritoResource:

```python
class UserResource(ModelResource):
    restritos = fields.ToManyField('geral.api.resources.RestritoResource', 'restrito_set', related_name='usuario', null=True)

    class Meta:
        queryset = User.objects.all()
        fields = ['username', 'email', 'first_name', 'last_name']
        authentication = Authentication()
        authorization = Authorization()
        always_return_data = True
        validation = FormValidation(form_class=UserValidationForm)
        filtering = {
            'username': ALL,
        }

class RestritoResource(ModelResource):
    usuario = fields.ForeignKey(UserResource, 'usuario', full=True)
    titulo = fields.ForeignKey(TituloResource, attribute='titulo')

    class Meta:
        allowed_methods = ['get', 'post', 'put', 'delete', 'patch']
        authentication = Authentication()
        authorization = Authorization()
        queryset = Restrito.objects.all()
        resource_name = 'restrito'
        always_return_data = True
        fields = ['usuario', 'titulo', 'ativa']
        serializer = Serializer()
        validation = FormValidation(form_class=RestritoValidationForm)
        filtering = {
            'usuario': ALL_WITH_RELATIONS,
        }
```
I need to validate a unique constraint and imagine a ModelForm can handle it, but when I submit a post like this.
```json
{
  "titulo": "/geral/api/v1/titulo/688/",
  "usuario": {
    "email": "johnny@mail.com",
    "nome": "johnny"
  }
}
```
I get this error:

"error_message": "int () argument must be a string or a number, not 'dict'"

If i remove validation from Meta everything works as expected.

It has some detail to work with FormValidation I'm leaving aside? Or I Unable to validate nested resources with Form?

Thanks

**Comment by SeanHayes** [comment]
Django forms don't support nested/related data like that, I think they need a model instance or a pk.

Based on the data you're posting, it looks like you're creating a new usuario, so uniqueness validation wouldn't make sense here anyway. You'd probably want to subclass FormValidation so you can skip uniqueness checking when usuario is a new instance, and when usuario is an existing instance you can get it's pk and verify uniqueness.
