### ISSUE TITLE
unexpected api_field_from_django_field behaviour

### ISSUE THREAD

**Issue by geiregjo** [django-tastypie/django-tastypie#1124]
The api_field_from_django_field function derives a Tastypie resource field from a Django model field. But both Django it's model DateField and DateTimeField are considered Tastypie resource DateTimeFields. This would make sense if Tastypie wouldn't have a DateField but it does...

Is this a bug or am I missing something?

The api_field_from_django_field function:
https://github.com/toastdriven/django-tastypie/blob/master/tastypie/resources.py#L1751

The Tastypie DateField:
https://github.com/toastdriven/django-tastypie/blob/master/tastypie/fields.py#L317

**Comment by SeanHayes** [comment]
Duplicated by PR #1238
