### ISSUE TITLE
Support custom reaction on UnsupportedFormat exception

### ISSUE THREAD

**Issue by troeger** [django-tastypie/django-tastypie#1154]
Several issues (#254, #985, #1015) argue around the problem that the UnsupportedFormat exception from the serializer ends up in an HTTP 500 error. This HTTP result code is intended for true server errors, meaning that the server-side implementation has an unexpected problem (== exception), whereas the HTTP request may even be fine. 

My argumentation here is that this is not consistent with the other parts of Tastypie, were the requestor can be clearly blamed for sending something wrong. Since the reaction in such a situation is a developer decision - e.g. I would like to return 415 instead of 500 -, my proposal is to add an official hook for reacting on such problems.

If that would be agreeable, I offer to prepare a patch the simply extends the implementation of the wrapper method (https://github.com/toastdriven/django-tastypie/blob/master/tastypie/resources.py#L192) to call such a hook function. Other ideas are welcome.

**Comment by SeanHayes** [comment]
Todo: In _handle_500, except UnsupportedFormat and return proper 4xx error.
