### ISSUE TITLE
DateField and DateTimeField fields don't honor timezones

### ISSUE THREAD

**Issue by kmike** [django-tastypie/django-tastypie#118]
I was bitten by this while implementing client-side code: chrome serializes javascript Date objects to '2011-03-30T18:00:00.000Z' format (it converts local time to UTC, the format is valid iso8601). The code reads data from API (it is returned in settings.TIME_ZONE timezone), creates Date object from this data and then eventually sends it back (with representation converted to UTC). Tastypie is somewhere loosing the timezone information during save so the time and the date becomes incorrect. 

I think dates with timezone information should be converted to django's current timezone before writing them to DB (in hydrate method?). 

Sample implementation (introducing pytz dependency):

    import dateutil
    import pytz
    from tastypie import fields
    from django.conf import settings
    
    def string_to_local_datetime(value):
        parsed = dateutil.parser.parse(value)
        try:
            django_tz = pytz.timezone(settings.TIME_ZONE)
            return parsed.astimezone(django_tz)
        except ValueError: # datetime without timezone information
            return parsed
    
    
    class TzDateTimeField(fields.DateTimeField):
        """
        A datetime field that honors timezone information.
        """
        def hydrate(self, bundle):
            value = fields.ApiField.hydrate(self, bundle)
    
            if value and not hasattr(value, 'year'):
                try:
                    # Try to rip a date/datetime out of it.
                    value = string_to_local_datetime(value)
                except ValueError:
                    pass
    
            return value

**Comment by georgedorn** [comment]
The referenced patch appears to fix the original issue, which is that tastypie was discarding POSTed timezone info.

If there's a large number of circumstances in which Tastypie is returning the wrong date/datetime, open a new issue detailing some of them so we can confirm and fix them.

There's a related, likely cantfix issue for how to both convert all POSTed timezones to the one given in the app's settings (e.g. for sorting in db queries) vs how to always show the original one vs how to present the user with their desired TZ, if the developer wants this at all.
