### ISSUE TITLE
Resource checking introduced in 0.11.1 doesn't honor multi table inheritance.

### ISSUE THREAD

**Issue by oliverandrich** [django-tastypie/django-tastypie#1184]
I have a problem with the new resource checking introduced in 0.11.1.

> Tastypie previously would accept a relation URI & solely parse out the identifiers, ignoring if the URI was for the right resource. Where 'user': '/api/v1/users/1/', would be accepted as a User URI, you could accidentally/intentionally pass something like 'user': '/api/v1/notes/1/', (notes rather than users), which would assign it to the User with a pk=1. Tastypie would resolve the URI, but proceed to only care about the kwargs, not validating it was for the correct resource.
> 
> Tastypie now checks to ensure the resolving resource has a matching URI, so these cases of mistaken identity can no longer happen (& with quicker lookups). Thanks to Sergey Orshanskiy for the report!

In my application I use inheritance for models.

``` python
class BaseExporter(models.Model):
    ...
class OnlineExporter(BaseExporter):
    ...
class PrintExporter(BaseExporter):
    ...
```

And use a reference to BaseExporter in a ForeignKey in some other model.

``` python
class ExportLogEntry(models.Model):
    ...
    exporter = ForeignKey('BaseExporter', null=True)
    ...
```

Assigning an instance of OnlineExporter or PrintExporter works just fine for djangos own ORM. But the new checking inside tastypie prohibits the creation of new ExportLogEntry instances based on a JSON document like this.

``` json
{
  ...
  "exporter" : "\/api\/v1\/onlineexporter\/1\/",
  ...
}
```

It only works, if a resource uri for a baseexporter is used. I think this is to much security checking and doesn't honor the inheritance feature of django.

**Comment by SeanHayes** [comment]
The resource name checking is staying in, but I'd be fine with allowing subtypes to match if someone could write a PR with a unit test.
