### ISSUE TITLE
on post I get HTTP/1.0 302 FOUND

### ISSUE THREAD

**Issue by ikresoft** [django-tastypie/django-tastypie#1218]
Why I get 302 result for every post/put request. I try also curl --dump-header - -H "Content-Type: application/json" -X POST --data '{"employee": "/api/v1/employee/1", "card_id":"222222"}' http://domain/api/v1/inoutjournal/
but same result 302 is returned.

**Comment by adrian410** [comment]
Hello i have the same problem. I want to access " http://localhost:8000/api/v1/reservation/" but instead i get a redirection to "/fr/api/v1/reservation/".

How can i solve this problem ? I have to disable the lang midleware to make it work or is there an alternative solution ?

My request :
`curl --dump-header - -H "Content-Type: application/json" -X POST --data '{ "origine": { "address": "Brest, France", "location": "SRID=4326;POINT (-4.486247100000014 48.3902557)" }, "destination": { "address": "Brest, France", "location": "SRID=4326;POINT (2.352579500000047 48.8572345)" }, "date": "24/02/2017T14:35", "car": "bisness", "duree": "5 heures 39 minutes", "distance": "592 km" }' http://localhost:8000/api/v1/reservation/`

My response:
"HTTP/1.0 302 Found
Date: Tue, 21 Feb 2017 15:48:26 GMT
Server: WSGIServer/0.1 Python/2.7.12
Vary: Cookie
Content-Type: text/html; charset=utf-8
Location: /fr/api/v1/reservation/"

**Comment by georgedorn** [comment]
That is also the language middleware redirecting your request to the french language endpoint.
