### ISSUE TITLE
get_via_uri not working for alphabetic ids that contain the resource name

### ISSUE THREAD

**Issue by fela** [django-tastypie/django-tastypie#1239]
Suppose I have a user whose id is `'myusers'` calling `get_via_uri` with `/v1/users/myusers/` won't work as espected. 

The function will try to get the id by removing `/v1/users` from the string but since d6cf75b134ccad4a174cfebdf33cddc11183d7af it will start searching from the right and in the above case will find the wrong instance of `"users"` and remove the whole string.

**Comment by sanketsaurav** [comment]
Any updates on this patch being merged to master?

**Comment by pmelet** [comment]
I still have to write tests, but had not time recently to do so
