### ISSUE TITLE
Option for POST to update existing matching resource

### ISSUE THREAD

**Issue by quantoid** [django-tastypie/django-tastypie#1241]
It's often useful to have an idempotent version of POST that will update an existing object if certain fields match, rather than always creating a new one. This makes it easy for clients to POST again and still get the same result, e.g. if something went wrong the first time. 

Maybe the bundle could be hydrated first to populate all the fields and resolve any related fields, then it's just a case of replacing the bundle.obj with any that matches specific fields (either all fields provided in the request, or a sub-set defined for the resource).

Could be done with Meta properties:

    class Meta:
        post_will_update = True
        post_match_fields = ['name', 'date']

Or a method to replace bundle.obj with any existing resource that matches the hydrated-but-not-saved bundle.obj:

    def obj_matching(self, bundle):
        try:
            # Replace with existing object with same name and date.
            bundle.obj = MyModel.objects.get(name=bundle.obj.name, date=bundle.obj.date)
        except MyModel.DoesNotExist:
            pass
        return bundle

**Comment by gulfpearl** [comment]
Isn't this already what POSTs do when you include the primary key field in the post? They update the existing object.

**Comment by SeanHayes** [comment]
This really isn't what POST is supposed to do, the HTTP docs specifically say POST is not idempotent. If something goes wrong (a 5xx return code) you should rollback the transaction or just not save the data.

I'd recommend returning a 400 error if someone tries to create a duplicate resource. I think this is the existing behavior if your model has unique or unique_together fields.

You can also use PUT to create resources using a specific pk, which is idempotent.

**Comment by SeanHayes** [comment]
If you really want this behavior in your api, you can create your own MyResource(ModelResource) class that your other resources inherit from.

**Comment by quantoid** [comment]
Okay maybe there's another way then. To give more details, what I want to do is allow clients to POST new resources that refer to other resources without first having to get the URI of those other resources. This is so they only have to do one POST rather than a complex sequence of requests.

For example:

    POST /api/release {"product": {"name": "Widget"}, "version": "1.2.3"}

I want this to create a new product resource unless there's already one called "Widget", in which case I want it to use that existing one.

**Comment by SeanHayes** [comment]
If no pk is provided, resources generally try to look up existing objects based on unique data. You can also change the lookup methods on your product resource to search by name.
