### ISSUE TITLE
RemovedInDjango18Warning: commit_on_success is deprecated in favor of atomic

### ISSUE THREAD

**Issue by EarlGlynn** [django-tastypie/django-tastypie#1250]
What does this mean?  Is this safe to ignore, or what do I do about the warning?

/opt/virtualenv/DjangoEnv/lib/python2.7/site-packages/tastypie/resources.py:2210: RemovedInDjango18Warning: commit_on_success is deprecated in favor of atomic.
  @transaction.commit_on_success()

Django==1.7.1
django-tastypie==0.12.1

**Comment by kciredor** [comment]
@georgedorn how about a fix? :)

**Comment by zxwild** [comment]
Django 1.8a1 is here, and tastypie doesn't work (1.8 will an LTS release, fix is wanted)

**Comment by coagulant** [comment]
Anyone willing to review PR #1274 (by @georgedorn) with preliminary Django 1.8 support?

**Comment by georgedorn** [comment]
Fixed by #1274, probably.
