### ISSUE TITLE
0.12 drops support for < django v1.5?

### ISSUE THREAD

**Issue by justinabrahms** [django-tastypie/django-tastypie#1254]
The release notes for [0.12](https://django-tastypie.readthedocs.org/en/latest/release_notes/v0.12.0.html) suggest that support for django 1.7 was added, but fails to mention that it breaks existing installations running on django 1.5 + south as the migrations have changed. It would be nice if that were noted a little more prominently (or at all) in the release notes.

**Comment by georgedorn** [comment]
All of your south migrations will break when transitioning from 1.5 to 1.7+ unless you have upgraded south and continue using it.

If you aren't using the APIKey model, this is irrelevant.  

If you are, you can either continue using (updated) south or export your existing keys, drop the tables, uninstall south (removing it from INSTALLED_APPS) and run django's migration tool with manage.py migrate.  Then re-import the keys.  Note that if you have other apps using south as well, this will break those as well.
