### ISSUE TITLE
Invalid resource lookup data provided (mismatched type).

### ISSUE THREAD

**Issue by Tempster102** [django-tastypie/django-tastypie#1273]
resources.py:

    class UserProfileResource(ModelResource):
        class Meta:
            queryset = Profile.objects.all()
            allowed_methods = [
                'get',
                'post'
            ]
            resource_name = 'user/profile'
            authentication = SessionAuthentication()
            authorization = DjangoAuthorization()

urls.py:

    v1_api = Api(api_name='1.0')
    
    v1_api.register(AuthenticationResource())
    v1_api.register(SessionUserResource())
    v1_api.register(SessionUserProfileResource())
    v1_api.register(UserResource())
    v1_api.register(UserProfileResource())
    
    urlpatterns = patterns('',
                           url(r'^api/', include(v1_api.urls)),
    )
    
    if settings.DEBUG:
        admin.autodiscover()
    
        urlpatterns += patterns('',
                                url(r'^grappelli/', include('grappelli.urls')),
                                url(r'^admin/', include(admin.site.urls)),
        )

Browsing to /api/1.0/user/profile/ throws "Invalid resource lookup data provided (mismatched type)." I've been searching for days but can't seem to fix this :/ 

Change "resource_name = 'user/profile'" to say "resource_name = 'user_profile'"; without the slash int he resource name works fine.

**Comment by SeanHayes** [comment]
It's probably because there's a slash in the resource name.

Is UserResource.Meta.resource_name by any chance 'user'? The Django url resolver is probably hitting that resource before UserProfileResource. Try registering UserProfileResource before UserResource.

**Comment by Tempster102** [comment]
UserResource is 'user' and changing the register didn't work :(

I know I could remove the slash but it didn't feel like it was following the 'restful' way which drives my OCD nuts.

Thanks!

**Comment by Tempster102** [comment]
urlpatterns = patterns('',
                           url(r'^api/', include(AuthenticationResource().urls)),
                           url(r'^api/', include(SessionUserResource().urls)),
                           url(r'^api/', include(SessionUserProfileResource().urls)),
                           url(r'^api/', include(UserProfileResource().urls)),
                           url(r'^api/', include(UserResource().urls)),
    )

The above urls.py worked, but using Tastypie's API didn't when rearranging the classes, so I'll just go back to this and append 1.0 to it as a workaround.

**Comment by SeanHayes** [comment]
Thanks for posting your solution. We should change tastypie to respect the registration order.

**Comment by Tempster102** [comment]
Thanks for help! I'll close the issue, this is for work I'll take a look at Tastypie and see if I can fix it and submit a patch, but thats time pending.... racing to beat the support cutoff for Server 2000...

**Comment by SeanHayes** [comment]
You can always subclass Api and make self._registry an OrderedDict:
https://github.com/django-tastypie/django-tastypie/blob/master/tastypie/api.py#L27
