### ISSUE TITLE
Getting ValueError Sometimes

### ISSUE THREAD

**Issue by sankaet** [django-tastypie/django-tastypie#1297]
Hi,

Sometimes I get the following error

```ValueError: The view tastypie.resources.wrapper didn't return an HttpResponse object. It returned None instead.```

Any clue what might be going wrong? this does not happen all the time, only sometimes

**Comment by coagulant** [comment]
Any uncaught `requests` library exception will trigger this error.
Tastypie wrapper returns `None` if view exception was raised and it happened to have `response` attribute.

https://github.com/django-tastypie/django-tastypie/blob/256ebe1de9a78dfb5d4d6e938b813cf4c5c4ac1b/tastypie/resources.py#L232

**Comment by dotsbb** [comment]
@coagulant @sankaet please take a look at https://github.com/django-tastypie/django-tastypie/issues/1404

**Comment by SeanHayes** [comment]
Closed in favor of PR #1404. Thanks!
