### ISSUE TITLE
Patch not returning updated data for prefetched fields

### ISSUE THREAD

**Issue by scenting** [django-tastypie/django-tastypie#1300]
When patching a prefetched field of a resource  (configured as always_return_data), even though patch is correctly made, returned data is outdated, it returns the data from the prefetch cache.

This issue is fixed by the following PR: https://github.com/django-tastypie/django-tastypie/pull/1282 and is very similar to the bug fixed by the previous commit: https://github.com/django-tastypie/django-tastypie/commit/b78661d76d1e73e2d90a8a1bcfcae90fcafb50b1

**Comment by SeanHayes** [comment]
Fixed in #1282
