### ISSUE TITLE
Related objects are not updated - Django 1.8

### ISSUE THREAD

**Issue by Jyrno42** [django-tastypie/django-tastypie#1306]
Django 1.8 disabled the assignment of unsaved foreign key values to models. This causes setattr in full_hydrate to raise a ValueError which results in the model being added to bundle.related_objects_to_save.

In save_related the FK is loaded from bundle.obj attributes since the FK is always there for our model. This causes the further logic to always use the old value of our Related object.

see: https://docs.djangoproject.com/en/1.8/ref/models/fields/#django.db.models.ForeignKey.allow_unsaved_instance_assignment

**Comment by Jyrno42** [comment]
Please note: I temporaly fixed this by overwriting full_hydrate and using the following context manager to ensure that all fields are writable when doing a setattr call. 

```
class EnsureWritableAttribute(object):
    def __init__(self, obj, attribute):
        self.field = obj._meta.get_field(attribute)
        self.old_value = self.field.allow_unsaved_instance_assignment

    def __enter__(self, *args, **kwargs):
        self.field.allow_unsaved_instance_assignment = True

    def __exit__(self, *args, **kwargs):
        self.field.allow_unsaved_instance_assignment = self.old_value
```

**Comment by mlissner** [comment]
This looks like a dup of issue #1325 to me.

**Comment by coady** [comment]
It's similar to #1325, but can't be identical.  #1325 wasn't introduced until a commit for 1.8.4, after this issue was created.
