### ISSUE TITLE
use_in for related fields

### ISSUE THREAD

**Issue by marcelosalloum** [django-tastypie/django-tastypie#1310]
Hello guys, I am trying to apply use_in within fields of my related models. In other words, I'v the following models:
```
class UserLookAPI(ModelResource):
    look       = fields.ForeignKey('cards.api.v1.look.LookAPI', 'look', null=True, full=True)

class LookAPI(ModelResource):
    owner          = fields.ForeignKey('custom_profile.api.v1.user.UserAPI', 'owner', null=True, full=True, use_in='detail')
```
and when I show a list of `userlooks`, I'd like the `userlook.look` resource to behave like a list entry and not a detail entry, so the `userlook.look.owner` would not show up for lists of `userlooks`.

Is that possible?

**Comment by SeanHayes** [comment]
It's not currently possible. I'd have UserLookAPI.look point to a duplicate LookAPI resource that doens't have "owner" on it.

Or you could use a "use_in" callback function, and inspect bundle.request.path to see if it should get displayed.

**Comment by marcelosalloum** [comment]
Yep, I ended up using your first suggestion (duplicate LookAPI).

Thanks a lot!

**Comment by SeanHayes** [comment]
No problem!
