### ISSUE TITLE
Change ordering with GET parameters?

### ISSUE THREAD

**Issue by Galaf** [django-tastypie/django-tastypie#1319]
Hello, I would like to know if it is possible to define the ordering we want through a GET parameter.
For example: http://example.com/api/v1/myres/?ordering=myattr

**Comment by Galaf** [comment]
Nevermind. I'm stupid.

**Comment by georgedorn** [comment]
In case anybody gets here via search, ordering is explained in the docs here:
http://django-tastypie.readthedocs.org/en/latest/resources.html#ordering
