### ISSUE TITLE
TestApiClient does not allow testing of csrf token

### ISSUE THREAD

**Issue by rzelayafavila** [django-tastypie/django-tastypie#1326]
I am trying to test my API for instances where I want to check for csrf token (both for when the user is logged in and not logged in), but I also want to be able to make another test case where it does not check the csrf token when the user is passing an oauth token for OAuth authentication. I have looked in the documentation and in the source code, and I can not find any device that allows the TestAPIClient to do this. Can this be added?

I am using:
Python version 2.7.6
django-tastypie version 0.12.1
Django version 1.7.4

Thanks!

**Comment by SeanHayes** [comment]
Django's CSRF token is normally used in HTML form data, which is a format Tastypie doesn't support. Also, Tastypie resources use csrf_exempt.

If you really need to, you can specify it in a header: https://docs.djangoproject.com/en/1.7/ref/contrib/csrf/#ajax

Let me know if I've missed something and this issue needs to be reopened.
