### ISSUE TITLE
GEOS required to be installed now

### ISSUE THREAD

**Issue by honza** [django-tastypie/django-tastypie#1339]
This was introduced in this commit, I believe 9269046b922bad33480baf1cf083cce885b5474e

Tastypie will fail on load (Django server start) when GEO isn't installed.

**Comment by SeanHayes** [comment]
Thanks! Could you post a stack trace for the error?

**Comment by phoebebright** [comment]
In resources.py line 13
     from django.contrib.gis.db.models.fields import GeometryField

And used 1975

        if django.VERSION >= (1, 8):
            query_terms = query_terms | set(GeometryField.class_lookups.keys())

**Comment by SeanHayes** [comment]
Thanks, I thought that might be it.

We need those lines for things to work in Django 1.8+, so we'll have to catch the error. Could you tell me the error that gets raised?

**Comment by phoebebright** [comment]
This works for me:


try:
    from django.contrib.gis.db.models.fields import GeometryField
    use_geos = True
except:
    use_geos = False


1981        if django.VERSION >= (1, 8) and use_geos:

**Comment by phoebebright** [comment]
Done a pull request for this and also changed tests so they won't run if geos missing.

**Comment by SeanHayes** [comment]
Replaced by #1341
