### ISSUE TITLE
Release notes for 0.12.2

### ISSUE THREAD

**Issue by mlissner** [django-tastypie/django-tastypie#1345]
Just noticed that 0.12.2 is in pip now, but there aren't release notes in [the usual place](https://django-tastypie.readthedocs.org/en/latest/release_notes/index.html). Have they moved? Just a point release, but it's always good to know if anything changed.

**Comment by SeanHayes** [comment]
I think I'll write a script that helps prepare a release by adding a new changelog with all the changes since the last tagged Git commit.

**Comment by SeanHayes** [comment]
The release notes have been added to the repo, though I don't know how to update rtd.

**Comment by SeanHayes** [comment]
@toastdriven @georgedorn Do you guys know how to update https://django-tastypie.readthedocs.org/en/latest/ ?

**Comment by SeanHayes** [comment]
Looks like it happens automatically, albeit very slowly: https://readthedocs.org/projects/django-tastypie/
