### ISSUE TITLE
Per-Request Alterations To the Queryset doesn't work as described

### ISSUE THREAD

**Issue by camlee** [django-tastypie/django-tastypie#1352]
As per this Django ticket: https://code.djangoproject.com/ticket/11629 the functionality described by Tastypie here: http://django-tastypie.readthedocs.org/en/latest/cookbook.html#per-request-alterations-to-the-queryset doesn't work.

In particular, although the code runs fine right now (Django 1.7, Django 1.8), the time being used isn't what's implied by the documentation (it's the time when the queryset was created, not when the request occurred). Also, it seems in Django 1.9, this code will actually fail: https://docs.djangoproject.com/en/1.8/internals/deprecation/#deprecation-removed-in-1-9
(search "Passing callable arguments to querysets will no longer be possible").

**Comment by SeanHayes** [comment]
We'll update our docs. Thanks!
