### ISSUE TITLE
Many to Many (related_name) relationship not available for declaration in Resources's 'ToManyField'

### ISSUE THREAD

**Issue by redy** [django-tastypie/django-tastypie#136]
When there is a many to many model relationship in django through what may be called as a 'cross join' model/table...
   ..That relationship is not available for declaration in a Resource.

Example in..

http://pastebin.com/2NHvns4P

http://pastebin.com/euTDgVM2

From an API standpoint I get access Users's projects..and I do get a list of projects.. however they are not the onese the user is a member of.
 However if I go though user's team and team's projects then I able to get the correct projects.

**Comment by SeanHayes** [comment]
pastebin links no longer work. As far as I know this works.
