### ISSUE TITLE
Release 0.13.0

### ISSUE THREAD

**Issue by SeanHayes** [django-tastypie/django-tastypie#1362]
@georgedorn I'd like to release another version on PyPi before we remove <Django 1.7 support. Do you have permissions to do that?

**Comment by dan-passaro** [comment]
+1 if this includes code that will stop the deprecation warnings Django generates whenever I do anything because of code in Tastypie (I'm on Django 1.8)

**Comment by lorinkoz** [comment]
Can't we have a quick release just to make it work with Django 1.9?

**Comment by SeanHayes** [comment]
Latest release: https://pypi.python.org/pypi/django-tastypie/0.13.0

It removes Django <1.7 support since those version are no longer supported by Django itself.
