### ISSUE TITLE
Replace references to apply_authorization_limits and apply_limits from cookbook and code

### ISSUE THREAD

**Issue by SeanHayes** [django-tastypie/django-tastypie#1383]

**Comment by mattbriancon** [comment]
@SeanHayes mind filling this one out a bit? Happy to fix docs, just not sure what needs fixing.

**Comment by SeanHayes** [comment]
apply_authorization_limits appears a few times in the docs even though it's deprecated, possibly removed. We need to replace references to it in the docs with code that does the same thing, though I'm not sure what that is off the top of my head.

**Comment by SeanHayes** [comment]
Duplicate of #1045
