### ISSUE TITLE
DjangoAuthorization requires modify access on creating resources

### ISSUE THREAD

**Issue by ambientsound** [django-tastypie/django-tastypie#1391]
Hi, I'm using Tastypie with `ApiKeyAuthentication` and `DjangoAuthorization`. I'm creating a resource using `ModelResource`:

```
class ModelRunResource(resources.ModelResource):
    model = fields.ForeignKey('modelstatus.core.api.ModelResource', 'model')

    class Meta(BaseMeta):
        queryset = modelstatus.core.models.ModelRun.objects.all()
```

Here is the Django model:

```
class ModelRun(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    reference_time = models.DateTimeField()
    model = models.ForeignKey('Model')
    version = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True, editable=False)
    modified = models.DateTimeField(auto_now=True, editable=False)

    class Meta:
        unique_together = ('reference_time', 'model', 'version',)
```

The problem happens during resource creation. I only want the API user to be able to POST to `/api/v1/modelrun/`, not to grant modification access. This doesn't work: it is not sufficient to grant access to `modelrun.add`, it also needs access to `modelrun.change`.

Please don't hesitate to ask for more information if needed.

Best regards, @ambientsound

**Comment by SeanHayes** [comment]
Our DjangoAuthorization only checks for "add" permission for adding, perhaps something else is going on with your authentication backends.

It could also be that "change" is required to add your related model, or that tastypie is accidentally saving the object a second time in the same request, thereby requiring a change permission.

**Comment by miraculixx** [comment]
> It could also be that "change" is required to add your related model, 

indeed that's what happens, `ModelResource.save(https://github.com/django-tastypie/django-tastypie/blob/master/tastypie/resources.py#L2333)` calls `save_related()` which in turn calls `save()` on the related object -- if that model happen's to exist already it will require the `change` permission, which seems right. 

To avoid this try adding `readonly=True` to your `model` field. It means a new `model` has to be created using `ModelResource` directly, then posting a `ModelRunResource` with `model` set to the URI of the new model.

**Comment by SeanHayes** [comment]
Haven't heard any updates, closing.
