### ISSUE TITLE
Duplication issue with query using filter on M2M relation in Meta class for Resource.

### ISSUE THREAD

**Issue by OOPMan** [django-tastypie/django-tastypie#1393]
Hi all, I've encountered an odd issue that results in the output from a GET call containing duplicate objects due to the manner in which the Django query is constructed and yields rows.

For off, I'm using Django 1.7.9 with Tastypie 0.12.1. Database is Posgresql 9.4

The setup required to duplicate this issue is a little involved.

First off, the models:
```
class A(models.Model):
    pass

class B(models.Model):
    instances_of_a = models.ManyToManyField(A, related_name='instances_of_b', null=True, blank=True)
```

now for the problematic Resource definition:
```
class AResource(ModelResource):
    class Meta:
        queryset = A.objects.all()

class BResource(ModelResource):
    instances_of_a = fields.ManyToManyField(AResource, 'instances_of_a', full=True, null=True)

    class Meta:
        queryset = B.objects.filter(instances_of_a__isnull=False)
```

When a GET is performed against BResource, any instances of B that are associated with more than one A object via the instances_of_a M2M relation will be returned multiple times in the response from BResource. The number of times an instance of B will be returned is equal to the number of A objects associated with it by the instances_of_a M2M relation.

The reason for this is due to the SQL Django generates to produce the Queryset. The SQL in question looks like this
```
SELECT
"database_schema_name"."id"
FROM "B"
 INNER JOIN "A"
   ON ("B"."id" =
       "B_A_Assn"."B_id")
WHERE ("B_A_Assn"."A_id" IS NOT NULL);
```

The result of this SQL is the issue describe above wherein there will be duplicate items in the queryset.

Probably the simplest solution to this is to not use a related filter in the fashion described but I would image it would be possible to detect for this kind of condition and handle it?

**Comment by SeanHayes** [comment]
Use queryset = B.objects.filter(instances_of_a__isnull=False).distinct()

https://docs.djangoproject.com/en/1.9/ref/models/querysets/#django.db.models.query.QuerySet.distinct
