### ISSUE TITLE
Django 1.9 compatibility

### ISSUE THREAD

**Issue by rolandgeider** [django-tastypie/django-tastypie#1395]
I just tested a project of mine with django 1.9, there are some problems with ``same_origin`` which seems to have been removed:

```python
File "/[snip]/api/resources.py", line 18, in <module>
    from tastypie.resources import ModelResource
  File "/[snip]/local/lib/python2.7/site-packages/tastypie/resources.py", line 20, in <module>
    from tastypie.authentication import Authentication
  File "/[snip]/local/lib/python2.7/site-packages/tastypie/authentication.py", line 11, in <module>
    from django.utils.http import same_origin
ImportError: cannot import name same_origin
```

**Comment by yansal** [comment]
:+1:

**Comment by sigmyers** [comment]
yup, this is the only plugin blocking us for upgrading to 1.9... seems to be a light fix! Will try and file a pull request to the django-tastypie team if it's as harmless as I was thinking

**Comment by nim65s** [comment]
I have to say that my pull request fixes the `same_origin` issue, but does not makes tastypie compatible with django 1.9, because (at least) another thing has been removed (and this time it is documented): 

```python
from django.core.cache import get_cache
ImportError: cannot import name 'get_cache'
```

**Comment by SeanHayes** [comment]
I got our test suite passing with PR #1400. Let me know if you experience any issues.

**Comment by lorinkoz** [comment]
Any chance we get a release in pypi soon?

**Comment by SeanHayes** [comment]
Here you go: https://pypi.python.org/pypi/django-tastypie/0.13.0

**Comment by lorinkoz** [comment]
Thanks ;)
