### ISSUE TITLE
Error with default value for UUIDField primary key

### ISSUE THREAD

**Issue by brigantino2** [django-tastypie/django-tastypie#1397]
I'm getting an error with primary keys having a default value.
Let's consider a model with an `UUIDField` (new in django 1.8)
https://docs.djangoproject.com/en/1.9/ref/models/fields/#uuidfield
```python
import uuid
from django.db import models
class MyModel(models.Model)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
```
Docs suggest to set a `default=uuid.uuid4` to automatically generate a value for the field on object creation.
When we try to perform an update (i.e. PUT), a new empty instance of `MyModel` is created in `tastypie.resources.Resource.build_bundle` and, having the field a `default`, it is assigned a new `id`.
Therefore the update fails, since the newly created instance has a different `id` from the one of the object to update.

**Comment by SeanHayes** [comment]
What version are you using? I think someone reported this and I looked into it. The fix might be in master but not on PyPi.

**Comment by SeanHayes** [comment]
Related to #1323

**Comment by xyres** [comment]
Yes, installing from master fixes this issue.

**Comment by SeanHayes** [comment]
Thanks! We'll try to get a PyPi release out soon.

**Comment by brigantino2** [comment]
Confirmed, I was running pip 0.12.2, master branch fixes it. Thanks
