### ISSUE TITLE
`obj_update` will take one more database search when bundle.obj.pk is an int value

### ISSUE THREAD

**Issue by MidTin** [django-tastypie/django-tastypie#1413]
These code lines make `obj_update` function always raise NotFound when bundle.obj is not None:

        bundle_detail_data = self.get_bundle_detail_data(bundle) if bundle.obj else None
        arg_detail_data = kwargs.get(self._meta.detail_uri_name, None)

        if not bundle_detail_data or (arg_detail_data and bundle_detail_data != arg_detail_data):
        ....

The reason is `get_bundle_detail_data(bundle)` always return an int num and `kwargs.get(self._meta.detail_uri_name, None)` always return a str num, their returns must not be equal.

**Comment by SeanHayes** [comment]
Thanks for reporting, could you make a PR containing a failing unit test?

**Comment by MidTin** [comment]
Sorry, I make a mistake, `obj_update` will not raise NotFound when bundle.obj is not None.

But it will take one more database search when bundle.obj is not None and bundle.obj.pk is an int value.

For example:

    from django.db import models
    from tastypie.resources import ModelResource

    class Entry(models.Model):
       content = models.TextField()

    class EntryResource(ModelResource):
        def obj_update(self, bundle, kwargs):
            bundle.obj = self._meta.queryset.get(pk=kwargs['pk'])
            ...
            return super(EntryResource, self).obj_update(bundle, **kwargs)

        class Meta:
            queryset = Entry.objects.all()
            resource_name = 'entry'

In the case above, Entry's pk is an int number. We override the `obj_update`, take up the bundle.obj ourselves by `pk`, do something, and call the original `obj_update` with the bundle, it will take one more database search in the original `obj_update`. This reason is:

    def obj_update(self, bundle, skip_errors=False, **kwargs):
        """
        A ORM-specific implementation of ``obj_update``.
        """
        bundle_detail_data = self.get_bundle_detail_data(bundle) if bundle.obj else None
        arg_detail_data = kwargs.get(self._meta.detail_uri_name, None)

        if not bundle_detail_data or (arg_detail_data and bundle_detail_data != arg_detail_data):
            try:
                lookup_kwargs = self.lookup_kwargs_with_identifiers(bundle, kwargs)
            except:
                # if there is trouble hydrating the data, fall back to just
                # using kwargs by itself (usually it only contains a "pk" key
                # and this will work fine.
                lookup_kwargs = kwargs

            try:
                bundle.obj = self.obj_get(bundle=bundle, **lookup_kwargs)
            except ObjectDoesNotExist:
                raise NotFound("A model instance matching the provided arguments could not be found.")

`bundle_detail_data` is an int value and `arg_detail_data` is a str value, it will take one more database search after the compare between them.

**Comment by SeanHayes** [comment]
OK, there should be an existing testcase somewhere for this behavior, we just need to add assertNumQueries to it.

**Comment by mattbriancon** [comment]
Not 100% sure where the fix should go but here's a failing test:

```
diff --git a/tests/core/tests/resources.py b/tests/core/tests/resources.py
index 96b670e..ccd2937 100644
--- a/tests/core/tests/resources.py
+++ b/tests/core/tests/resources.py
@@ -3924,7 +3924,9 @@ class ModelResourceTestCase(TestCase):
         note_bundle = note.build_bundle(obj=note_obj)
         note_bundle = note.full_dehydrate(note_bundle)
         note_bundle.data['title'] = 'Whee!'
-        note.obj_update(note_bundle, pk=1)
+
+        with self.assertNumQueries(1):
+            note.obj_update(note_bundle, pk=1)
         self.assertEqual(Note.objects.all().count(), 6)
         numero_uno = Note.objects.get(pk=1)
         self.assertEqual(numero_uno.title, u'Whee!')
@@ -3932,6 +3934,17 @@ class ModelResourceTestCase(TestCase):
         self.assertEqual(numero_uno.content, u'This is my very first post using my shiny new API. Pretty sweet, huh?')
         self.assertEqual(numero_uno.is_active, True)

+        # same setup as above, just need to test with `'1'` as the pk
+        note = NoteResource()
+        base_bundle = Bundle()
+        note_obj = note.obj_get(base_bundle, pk=1)
+        note_bundle = note.build_bundle(obj=note_obj)
+        note_bundle = note.full_dehydrate(note_bundle)
+        note_bundle.data['title'] = 'Whee!'
+        with self.assertNumQueries(1):
+            note.obj_update(note_bundle, pk='1')
+        self.assertEqual(Note.objects.all().count(), 6)
+
         self.assertEqual(Note.objects.all().count(), 6)
         note = RelatedNoteResource()
         related_obj = note.obj_get(base_bundle, pk=1)
```
