### ISSUE TITLE
Forbid ApiKeyAuthentication as URL parameters

### ISSUE THREAD

**Issue by yansal** [django-tastypie/django-tastypie#1425]
I am aware that there are 2 ways to authenticate users with ApiKeyAuthentication: with Authorization header or with URL parameters.

I would like to know if there's a way to forbid users to authenticate with URL parameters.

**Comment by georgedorn** [comment]
Create your own subclass of ApiKeyAuthentication and override the extract_credentials() method to only look in request.META.

https://github.com/django-tastypie/django-tastypie/blob/master/tastypie/authentication.py#L175 is the original method.

**Comment by yansal** [comment]
Thank you!
