### ISSUE TITLE
Update pypi version

### ISSUE THREAD

**Issue by prokaktus** [django-tastypie/django-tastypie#1426]
Currently Pypi version tastypie 0.13.0 contains the wrong assertion in `tests.py`:
```
    def assertHttpAccepted(self, resp):
        """
        Ensures the response is returning either a HTTP 202 or a HTTP 204.
        """
        self.assertIn(resp.status_code, [202, 204])
        self.assertNotIn('Content-Type', resp)
```

Second assert fixed in #1416, but Pypi-version is a little bit outdated and it breaks tests logic.

**Comment by SeanHayes** [comment]
https://pypi.python.org/pypi/django-tastypie/0.13.1
