### ISSUE TITLE
In Python 3, ApiKey list in admin is not useful

### ISSUE THREAD

**Issue by vtbassmatt** [django-tastypie/django-tastypie#1459]
The ApiKey list in the admin isn't useful under Python 3 because ApiKey only implements __unicode__. Other models in `tastypie.models` use the `@python_2_unicode_compatible` decorator, but for some reason ApiKey does not. I'll prepare and submit the 2-line fix.

**Comment by vtbassmatt** [comment]
Nevermind, I see that https://github.com/django-tastypie/django-tastypie/pull/1262 addresses this and more.

**Comment by SeanHayes** [comment]
Thanks!
