### ISSUE TITLE
Option to avoid computing total count

### ISSUE THREAD

**Issue by 8one6** [django-tastypie/django-tastypie#1466]
Right now, the `Paginator` class computes a `total_count` of all objects to return as part of the `"meta"` portion of the api response.  In most casees, I think that seems pretty reasonable.  However, for very large databases (I have a use case in mind with tens or hundreds of millions of rows), the act of simply computing an accurate count can be very slow.  This is already acknowledged in the docs, where there is a very thoughtfully written implementation of a reasonable "approximate count" solution with Postgres in mind (not sure how well it works for other backends).

With that in mind, would it make sense to add a configurable option to avoid computing totals in the `"meta"` section of the api response?  I.e. if you chose `compute_totals=False` then the API simply wouldn't compute totals at all.  But the default could be `compute_totals=True`.

**Comment by mattbriancon** [comment]
I'd prefer to see a setting to define the default `paginator_class` on resources.

```python
TASTYPIE_DEFAULT_PAGINATOR_CLASS = 'myapp.NoTotalPaginator'
```

Similar settings could be added for other `ResourceOptions` attributes as it's a pretty common to authentication and authorization across an entire project.

```python
    serializer = Serializer()
    authentication = Authentication()
    authorization = ReadOnlyAuthorization()
    cache = NoCache()
    throttle = BaseThrottle()
    validation = Validation()
    paginator_class = Paginator
```

**Comment by SeanHayes** [comment]
If you want several Resources to use the same default settings, I'd recommend creating a base Meta class and inheriting your Resource.Meta class from that.
