### ISSUE TITLE
"y-m-dTh:m:s" isn't parseable anymore

### ISSUE THREAD

**Issue by olasfar** [django-tastypie/django-tastypie#1478]
Hey guys,

This commit 8cc07f64 looks to improve the performance of how datetime fields are parsed but it introduced a new issue, example: {{2010-11-10T03:07:43}} isn't parseable anymore:
```
In [1]: from django.utils import datetime_safe
In [2]: value = "2010-11-10T03:07:43"
In [3]: from tastypie.utils import make_aware
In [4]: year, month, day = value[:10].split('-')
In [5]: hour, minute, second = value[10:18].split(':')
In [6]: make_aware(datetime_safe.datetime(int(year), int(month), int(day), int(hour), int(minute), int(second)))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-3f6b5d00106f> in <module>()
----> 1 make_aware(datetime_safe.datetime(int(year), int(month), int(day), int(hour), int(minute), int(second)))
ValueError: invalid literal for int() with base 10: 'T03'
```
The docsting says that the code should handle this case while it's not the case actually https://github.com/django-tastypie/django-tastypie/blob/master/tastypie/fields.py#L384

Why there is no unit test covering this case ?

Cheers!

**Comment by m-vdb** [comment]
wow this is pretty serious, and it doesn't work with all dates patterns, like `2010-11-10 03:07:4` of instance... The fix is pretty easy but how do we avoid regression?

**Comment by m-vdb** [comment]
cc @SeanHayes

**Comment by SeanHayes** [comment]
Sorry about this, I'll get it resolved tonight. I'll also have to look into why our tests didn't pick up the error.

**Comment by SeanHayes** [comment]
Tests didn't pick this up because the test value ended in zeros.

This has been fixed.

**Comment by m-vdb** [comment]
thanks @SeanHayes for your reactivity! will there be a version bump soon?

**Comment by SeanHayes** [comment]
I believe so, one of the other contributors is putting together a release for Django 1.10 support.
