### ISSUE TITLE
N+1 queries in dehydrate of m2m

### ISSUE THREAD

**Issue by tarungarg546** [django-tastypie/django-tastypie#1487]
Hi,

Awesome blowsome project :). Thanks for giving this much up for community.

But as every journey for everyone is not as smooth, so ...

We have a tastypie resource that depends on some other resource through m2m relationship.

Now we are doing some work in `save_m2m`, something like below

```
def save_m2m(self, bundle):
     super(ourResource, self).save_m2m(bundle)
     //some work
     return bundle
```

and after  that, before sending any data to client, it goes into dehydrate of m2m resource and under that, it have code something like 

```
self.m2m_resources = []
    m2m_dehydrated = []

    # convert the_m2ms to a QuerySet if it isn't already
    if type(the_m2ms) != QuerySet:
        the_m2ms = the_m2ms.all()

    # expects a QuerySet unlike super dehydrate method
    for m2m in the_m2ms:
        m2m_resource = self.get_related_resource(m2m)
        m2m_bundle = Bundle(obj=m2m, request=bundle.request)
        self.m2m_resources.append(m2m_resource)
        m2m_dehydrated.append(self.dehydrate_related(m2m_bundle, m2m_resource, for_list=for_list))
```

Now in it the last line `self.dehydrate_related` is causing n+1 queries since it executes each time the loop runs.

Also btw, we have already done `prefetch_related` on our querySet in Meta class. for related resource
Something like 

```
class Meta:
    detail_allowed_methods = ['patch']  
    list_allowed_methods = ['get', 'post']
    queryset = table.objects.using('default').select_related('table2') \
        .prefetch_related(
            Prefetch('table3',
                     queryset=table3.objects.select_related('table4', 'cols')
                     .prefetch_related('options', 'options__options')
                     .only(*FIELDS_TO_QUERY_API)
                     ),
            Prefetch('items',
                     queryset=Item.objects.select_related('item_data')
                     .only(*FIELDS_TO_QUERY_API)
                     ),
            'tableX',
            'tableX__options'
    )\
        .only(*FIELDS_TO_QUERY_PM_API)

    fields = (... our fields ...)
    serializer = UJsonSerializer()
    validation = ModelFormValidation(form_class=resourceForm)
    always_return_data = True
    ordering = ['started_at']
    filtering = {
        'status': ('in',)
    }
    cache = OnlyCacheHeaders()
```

And  currently n+1 queries happening when we do `post-list` in tastypie.

I am not sure how to debug and find root cause of issue.

**Comment by SeanHayes** [comment]
Sounds like `self.dehydrate_related` is accessing some related data that isn't included in your `prefetch_related` call. I'd look at what SQL table is being access as a clue to which relation that is.

**Comment by tarungarg546** [comment]
@SeanHayes Thanks for reply and library.

I profiled our queries and found the traceback using django-silk.

I found that repeated query happening at two locations in code.
- When the_m2ms is evaluated at `for m2m in the_m2ms:` in dehydrate of m2m.
- When the given m2m has a ToOne resource related to it. It calls `dehydrate` of ToOneField which in turn calls a method `getattr(foreign_obj, attr, None)` these are two places where repeated queries happening.

And the data which those are accessing are already in prefetched/select_related.

Let me explain a bit more, we have our Resource class like this : - 
```py
class tableResource(ModelResource):
    items = ToManyField(ItemResource, attribute='items', full=True, null=True)
    class Meta:
      queryset = table.objects.using('default').select_related('table2') \
        .prefetch_related(
            Prefetch('table3',
                     queryset=table3.objects.select_related('table4', 'cols')
                     .prefetch_related('options', 'options__options')
                     .only(*vc)
                     ),
            Prefetch('items',
                     queryset=Item.objects.select_related('item_data')
                     .only(*vcx)
                     ),
            'tableX',
            'tableX__options'
       )\
        .only(*fdv)

      fields = (... our fields ...)
      always_return_data = True
```

Now as a part of `full_dehydrate` tastypie traverse each field in `self.fields`, now in process it comes to `items` filed ,tastypie saw this a M2m resource and calls dehydrate of m2m.
Now inside that dehydrate we have for loop in tastypie which is like 
`for m2m in the_m2ms:`, now at this moment since the_m2ms was a queryset it evaluates itself and fire a query doing a join on `items` and `table_items` which makes no sense[**This is an extra query**].

Now in item it iterate over all item and goes to `dehydrate_related` for each which builds a bundle and called `full_dehydrate` on `related_resource` which in our case is `itemResource`. Inside `full_dehydrate` it again iterates over `self.fields`[**self here is itemResource**]. and found `itemdata` as having toOne relation with `item` so it calls `ToOne.dehydrate` and inside that we have `getattr(foreign_obj, attr, None)` which fires an query on `item_data` model[** which is also extra **].

Note both item and item_data are part of queryset's `prefetch/select_related`

**Comment by gjcourt** [comment]
I run into this issue all the time. Sometimes I can use `select_related` or `prefetch_related`. Sometimes I run lots of raw queries in a list endpoint, so I've developed a pattern to add additional information on list views.

```python
class ModelResource(Resource):

    ...

    def obj_get_list(self, bundle, **kwargs):
        objects = super(ModelResource, self).obj_get_list(bundle, **kwargs)
        self.obj_attach_extra_data(objects, request=bundle.request)
        return objects

    def obj_get(self, bundle, **kwargs):
        obj = super(ModelResource, self).obj_get(bundle, **kwargs)
        self.obj_attach_extra_data([obj], request=bundle.request)
        return obj

    def obj_attach_extra_data(self, objects, request=None, **kwargs):
        cursor = connection.cursor()
        # Fetch external data
        self._data = list(cursor.execute(...).fetchall())

    def attach_data(self, bundle):
        try:
            bundle.data['extra'] = self._data
        except AttributeError:
            bundle.data['extra'] = []
        
    def dehydrate(self, bundle):
        self.attach_data(bundle)

        ...

        return bundle
```
