### ISSUE TITLE
Cut a release compatible with Django 1.11

### ISSUE THREAD

**Issue by adamzap** [django-tastypie/django-tastypie#1490]
Any chance we could get an official release since #1480 was merged?

Thanks!

**Comment by georgedorn** [comment]
I wasn't sure I had the ability to publish to PyPI, but evidently I do now.  I'll have a look later this week to see what PRs can be merged and then cut a release for 1.10.

@adamzap If you feel like helping, you could have a look at open PRs and comment on those that seem possible to include in the release.  If you don't have time, that's fine, but if you do that'd speed things up a bit.

**Comment by adamzap** [comment]
Sure! I took a look at all PRs assigned to the `v0.13.4` milestone, and unfortunately, they are all waiting of follow up from the person that opened them (merge conflicts, needs tests, etc). I could open new PRs for some of them if they seem worthwhile.

However, I think #1485 can be merged immediately since it's a simple documentation fix, and #1320 can be closed since it includes no changes.

Let me know what you think. I'll keep looking around.

Are you on IRC somewhere? Maybe we can chat about how I can be more helpful.

Also, thanks to my employer, [Crossway](https://www.crossway.org/), for allowing me to spend work time on this!

**Comment by SeanHayes** [comment]
The milestones are pretty much meaningless, I assigned issues to them as a way of prioritizing them for myself, but I haven't had time to work on those releases. Generally speaking, 0.13.4 issues should be done before 0.14.0 issues and are less likely to break backwards compatibility. The 1.0.0 milestone was there before I joined, some of them maybe should be moved up in priority.

**Comment by adamzap** [comment]
Ah ok. 90 of the 122 open PRs have merge conflicts. I'm not sure what you want to do about those. For what it's worth, Django's maintainer asks for follow-up, waits for a period of time, and closes the request if the author doesn't respond.

Here are the remaining 32 PRs with some assessment from me:

- #236 (Not finished)
- #271 (Seems ready, needs release note)
- #320 (Documentation fix, seems ready)
- #379 (Design decision needed)
- #540 (Buggy implementation)
- #575 (Further changes needed?)
- #662 (Documentation fix, needs review)
- #695 (Needs tests)
- #761 (Seems ready)
- #798 (Documentation fix, needs review)
- #834 (Adds a single test, seems ready)
- #923 (Needs review)
- #989 (Needs fix and tests)
- #1014 (Needs review and design decision)
- #1127 (Tests fail)
- #1166 (Needs more comprehensive fix)
- #1192 (Seems ready)
- #1195 (Tests fail, need test)
- #1242 (Needs test)
- #1256 (Patch needs improvement and test)
- #1265 (Needs follow-up from maintainer)
- #1279 (Needs test)
- #1320 (No diff)
- #1321 (Design decision needed)
- #1453 (Needs test)
- #1457 (Needs test)
- #1463 (Needs follow-up from maintainer)
- #1469 (Documentation fix, needs review)
- #1482 (Seems ready, might need review)
- #1483 (Patch needs improvement)
- #1485 (Documentation fix, seems ready)
- #1486 (Seems ready, needs further review)

I hope this is helpful!

I personally think Django 1.10 compatibility is enough for a release, but it's up to yall!

**Comment by SeanHayes** [comment]
I'd like to do the same and just close them due to inactivity, but a lot of them are for legitimate bugs so we need to keep a record of them.

**Comment by jvanveen** [comment]
Any news?

**Comment by Nijhazer** [comment]
Following up on this.

**Comment by ssjunior** [comment]
Following.

**Comment by john-clarke** [comment]
Following.

**Comment by aehlke** [comment]
Please just hit the "Subscribe" button to follow this thread. If you comment, you notify everyone else that you're subscribing. We're all interested :)

**Comment by gediminas-revel** [comment]
Any plans to support Django 1.11?

https://www.djangoproject.com/weblog/2017/apr/04/django-111-released/

**Comment by aehlke** [comment]
It seems there are Django 1.10 compatibility fixes that landed in master. It would help if someone could confirm whether tastypie master branch has issues with 1.11.

**Comment by cristianocca** [comment]
What's the status on this? Thanks.

**Comment by tdenmark** [comment]
+1

**Comment by alf182** [comment]
in Django 1.11 we have problems too, please update compatibility for django 1.11

**Comment by georgedorn** [comment]
TODO:

Release notes:
- Add note about preferring nulls to defaults when null=True and current value is None (#271)
- Update documentation about supported versions (1.8, 1.11, python 2.7 and 3.?)

Tests:
- Add python 3.6 to tox/travis test matrix.

Fixes:
- Silence a huge number of warnings.  #1486 might be a good place to start, but new ones exist under 1.11 regarding django 2.0.

**Comment by mattbriancon** [comment]
@georgedorn I'm happy to rebase #1486 or do whatever else needs doing to get things moving again.

**Comment by sp1rs** [comment]
Is tastypie supporting Django 1.11?

**Comment by georgedorn** [comment]
Release v0.14.0 was just uploaded to PyPI.  It includes explicit support for LTS versions of Django (1.8 and 1.11).  Django 1.9 and 1.10 almost certainly are compatible, but are unsupported.
