### ISSUE TITLE
API Updates instead of Creates if there is a single object in the database

### ISSUE THREAD

**Issue by ninapavlich** [django-tastypie/django-tastypie#1497]
I have a create endpoint for a certain object. If there is a single object already in the database, when I attempt to create another one with the API, it instead updates the single existing one.

I believe this is due to the code in lines 2091-2094 in resources.py. The logic goes that if there are not existing objects in the database it raises a DoesNotExist error. If there is more than one object in the database it raises as MultipleObjectsReturned error. But if there is a single object in the database, the single item in the database is returned.

![tastypie_create_objects_issue](https://cloud.githubusercontent.com/assets/408926/22163178/99f26194-df06-11e6-9a2e-40e8e59c6ef5.png)

This returns the object to the function put_detail (line 1407), which assumes that this is an update function on that single item instead of a create function.

Instead, I would expect it to check against the existence of a PK or ID on the bundle. Perhaps by using the detail_uri_name or something like that.

**Comment by georgedorn** [comment]
What HTTP method and URL are you using?  I need more information to replicate this issue.

**Comment by georgedorn** [comment]
@ninapavlich:
It should not be possible to PUT to a detail URL without a primary key.  That's the definition of a detail URL.  Are you using a custom URL or a custom key?

Can't reproduce without more details.
