### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by spacecar2000** [django-tastypie/django-tastypie#1500]
Hello Django-tastypie security,

I sent an email a week ago to the security email address: tastypie-security@googlegroups.com but I have not heard a response, so I am posting my email here.

My name is Peter Robinson and I am a product security expert at Intel working in Longmont, Colorado.

I cloned your latest git repository at: https://github.com/django-tastypie/django-tastypie

I ran your latest version of Django-tastypie, version 0.13.3  through our Static Code Analyzer  (SCA) tool.

I wanted to report to you the findings of our SCA tool. The SCA tool that we are using is called Checkmarx

Please see my “Conclusions” remarks after each potential issue listed below.

I am interested in hearing your thoughts about each of the potential vulnerability issues.

Thanks for your time ,

Peter

Checkmarx found 2 High Vulnerabilities and 1 Low Vulnerability.

Because of the nature of a static code analysis tools in general, false positives may be found.

Scan Results Details

1 - Reflected XSS All Clients

 
![1](https://cloud.githubusercontent.com/assets/20309295/23366555/5b8339de-fcc4-11e6-99be-e6f036ccf6e5.png)

Conclusion:  In the api function: top_level, lines 158 to 166 could potentially be used to have a defined javascript function run resulting in
cross site scripting (Reflected). This is highly unlikely.

From the https://www.quora.com/What-is-the-difference-between-request-get-and-request-GET-get-in-django:

request.GET is a dictionary-like object containing all GET request parameters. This is specific to Django.
The method get() returns a value for the given key if key is in the dictionary. If key is not available then returns default value None. Read more here.
request.GET.get() is combination of above two using which key/values of a GET request can be accessed. This would be mostly used in Django Views.

2 – Second order SQL Injection

 
![2](https://cloud.githubusercontent.com/assets/20309295/23366559/5f1f8fc0-fcc4-11e6-87fe-17d68af71f01.png)

Conclusion:  This is most likely not a valid  security vulnerability because this is the prescribed method of writing custom Django admin commands from Django.
see: https://docs.djangoproject.com/en/1.10/howto/custom-management-commands/
In this case, the command would be run with: python manage.py backfill_api_keys
A user cannot “easily”  influence the result from the python list “User = get_user_model()”to cause SQL injection.
However, this would depend on how the ApiKey is used and whether or not a user can replace his own ApiKey with an arbitrary value.

3 – Information Exposure through an Error Message
![3](https://cloud.githubusercontent.com/assets/20309295/23366562/629b2132-fcc4-11e6-8080-8abc546209c3.png)

 
Conclusion:  This appears to be a valid error handling condition. Checkmarx is concerned that too much information is revealed to a user.
This is a Low vulnerability issue.

**Comment by georgedorn** [comment]
The first item is a legitimate concern.  Adding a milestone and tagging accordingly.

**Comment by georgedorn** [comment]
Further investigation reveals that the callback parameter is validated "according to the latest draft of the ECMAScript 5 Specification".

The doctests for the validation function weren't being run during the test suite; added that here: #1527
