### ISSUE TITLE
AttributeError: class Meta has no attribute 'object_class'.

### ISSUE THREAD

**Issue by sp1rs** [django-tastypie/django-tastypie#1517]
When used `Resource` as a super class to a model, it works fine. But if I use `ModelResource` then 

`AttributeError: class Meta has no attribute 'object_class'` is coming.

 If I add `queryset` in my `meta` then it work fine for both the Resource. But if i don't add `queryset` then it throws an error.

Here is the duplicate issue.  #1475 

The workaround is that i have added object_class=None in all my meta.

Is it a bug or Is it how it works?

**Comment by DonCarnohan** [comment]
I'm 90% sure this is a bug. this line should read "if meta and hasattr(meta, 'object_class') and meta.object_class:"

Or something along those lines...

**Comment by georgedorn** [comment]
ModelResource requires either object_class or queryset.  If queryset is set, it determines the object_class from it.  But if neither is set, it can't figure out the object name to use in urls or what fields to include in the payloads.  If you intend to dynamically build those on each request, don't use a ModelResource.

It's not a bug, it's a poor error message.

@sp1rs: can you post your Resource / ModelResource declarations?

**Comment by georgedorn** [comment]
"fixed" in #1475, in the sense that a better error message is provided.  Another PR is in the works to add an `abstract` flag to skip having to set `object_class = None`.
