### ISSUE TITLE
Tastypie requires libgeos?

### ISSUE THREAD

**Issue by chrisspen** [django-tastypie/django-tastypie#1530]
I recently upgraded Django-Tastypie to 0.14.0, and now I get the error:

    OSError: /usr/lib/libgeos_c.so.1: cannot open shared object file: No such file or directory

I've seen this before when I used a GIS database backend, but I haven't used any such backend in years, so I'm not sure why Tastypie would now suddenly require libgeos. How do I proceed without installing libgeos?

**Comment by georgedorn** [comment]
It shouldn't require it unless you're using the geo features.

Can you post the full traceback, along with the command you ran that resulted in the error?

**Comment by chrisspen** [comment]
I've resolved this. It was something unrelated. Sorry for the false alarm.
