### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by SKisContent** [django-tastypie/django-tastypie#1537]
I'm hitting what appears to be a logic error in the `dehydrate` method of `ToManyField` class in _fields.py_:
The code in question starts at line 856: 
```
        if the_m2ms is None:
            if not self.null:
                raise ApiFieldError("The model '%r' has an empty attribute '%s' and doesn't allow a null value." % (previous_obj, attr))

        if isinstance(the_m2ms, models.Manager):
            the_m2ms = the_m2ms.all()

        m2m_dehydrated = [
            self.dehydrate_related(
                Bundle(obj=m2m, request=bundle.request),
                self.get_related_resource(m2m),
                for_list=for_list
            )
            for m2m in the_m2ms
        ]
```
Let's say `the_m2ms` is `None` and `self.null` is `False`. The code will not raise an error, will not execute the `if isinstance` clause and will land on the `for` iteration. At this point a `TypeError: 'NoneType' object is not iterable` is thrown.

To replicate this, create a `ModelResource` subclass  with a self-referencing related field:
```class MyResource(ModelResource):
    children = fields.ToManyField('self', 'children', null=True, full=True)
```

**Comment by toto22450** [comment]
Hello @SKisContent,

I am currently facing the same issue. Did you find a solution ?

**Comment by Moliholy** [comment]
I seems it's been introduced in version 0.14.0. Take a look:
https://github.com/django-tastypie/django-tastypie/blob/v0.13.3/tastypie/fields.py#L859
https://github.com/django-tastypie/django-tastypie/blob/v0.14.0/tastypie/fields.py#L859

The question is: why?

**Comment by georgedorn** [comment]
> The question is: why?

Because there are no tests covering this situation, so a regression was inevitable.  If you could add a test in your PR that fails without your code change, I'll be happy to merge it and cut a new release (we need one for 'official' Django 2.0 compatibility anyway).

Without a test, this regression will almost certainly happen again.

**Comment by SKisContent** [comment]
Hey, toto22450,
I never did. I think I just worked around it.

**Comment by georgedorn** [comment]
@toto22450 @SKisContent 
I'm unable to replicate this issue in a unit test.  It appears to only be possible when using a callable attribute or a relationship specified with a string that returns `None`.  Can you post your `Resource` and the request that triggers the error?

**Comment by Moliholy** [comment]
@georgedorn I found what was happening with my own project: I was using an incorrect attribute name in a field that allows null. I fixed it, but I thought it might be useful to indicate the error, so I modified the PR.
