### ISSUE TITLE
Deal with CI flake8 errors: 'do not use bare except'

### ISSUE THREAD

**Issue by pawelswiecki** [django-tastypie/django-tastypie#1540]
Travis CI is using the newest flake8 version, that is 3.5.0. This version stared checking for bare exceptions (i.e. catch-all exceptions). See this PR https://github.com/django-tastypie/django-tastypie/pull/1539. The following errors were reported byt flake8 CI step:

```
./tastypie/authentication.py:79:9: E722 do not use bare except'
./tastypie/resources.py:2266:13: E722 do not use bare except'
./tests/core/tests/resources.py:852:9: E722 do not use bare except'
./tests/core/tests/resources.py:4550:9: E722 do not use bare except'
```

To make Travis happy and to make the code better this needs to be dealt with.

**Comment by georgedorn** [comment]
Marking this fixed by #1541
