### ISSUE TITLE
Is it safe to use Tastypie in production as it is still in beta ?

### ISSUE THREAD

**Issue by essadek** [django-tastypie/django-tastypie#1559]
Is it safe to use Tastypie in production ? 
What does it mean for the developer when you say :  

> Currently in beta (v0.14.1) but being used actively in production on several sites.

**Comment by georgedorn** [comment]
Yeah, it's fine to use in production, has been for many years.

We've never really figured out what collection of milestones would indicate it is time to bump major version numbers, and it's been reasonably stable for a long time, so a version bump for no reason would be more confusing than helpful.
