### ISSUE TITLE
Easier way to use Resource in views

### ISSUE THREAD

**Issue by cyberdelia** [django-tastypie/django-tastypie#156]
There should be [easier way](http://django-tastypie.readthedocs.org/en/latest/cookbook.html#using-your-resource-in-regular-views) to use Resource in views, especially to do javascript  [model bootstrapping](http://documentcloud.github.com/backbone/#FAQ-bootstrap).

Maybe something like a ``ResourceQueryset``than could ease querying and serialization ?

**Comment by SeanHayes** [comment]
Seems pretty easy already. A one liner would look something like:

    user_json = UserResource().get_detail(request, username=username).content
