### ISSUE TITLE
obj_update swallows pk kwarg

### ISSUE THREAD

**Issue by remoun** [django-tastypie/django-tastypie#158]
I'm trying to update a couple of fields via PUT to a detail URL. put_detail first tries obj_update, passing it the PK, but the latter loads the object then overrides the supplied kwargs with the values from the loaded model object (full_hydrate only consults the defined fields, so doesn't use 'pk' for the lookup), which overwites the 'pk' arg with an empty string in my case.

I got it to work by overriding obj_update to exclude 'pk' from being updated in lookup_kwargs:

```
@@ -1550,7 +1550,7 @@
                 lookup_kwargs.update(dict(
                     (k, getattr(bundle.obj, k))
                     for k in kwargs.keys()
-                    if getattr(bundle.obj, k) is not None))
+                    if k != 'pk' and getattr(bundle.obj, k) is not None))
             except:
                 # if there is trouble hydrating the data, fall back to just
                 # using kwargs by itself (usually it only contains a "pk" key
```

**Comment by xiaolong3105** [comment]
您好，您的邮件我已收到，我会尽快处理。
 
Best Wishes!
晓龙
