### ISSUE TITLE
0.14.2 tag on GitHub missing

### ISSUE THREAD

**Issue by jayvdb** [django-tastypie/django-tastypie#1582]
There havent been any changes since 0.14.2 , so I guess https://github.com/django-tastypie/django-tastypie/commit/60c0c6f4a8ed9ecd0600e9f59bb1ca857c0a6f43 or its parent is the final commit for it.

This is especially important for packagers because the sdist doesnt include the tests, so we need something else to fetch the test suite. e.g.

https://build.opensuse.org/package/show/devel:languages:python:django/python-django-tastypie

**Comment by georgedorn** [comment]
Added here: https://github.com/django-tastypie/django-tastypie/releases/tag/v0.14.2

**Comment by jayvdb** [comment]
Thanks so much - https://build.opensuse.org/request/show/678519 package being updated on openSUSE
