### ISSUE TITLE
v0.11.0 missing migration

### ISSUE THREAD

**Issue by nanmeng** [django-tastypie/django-tastypie#1589]
v0.11.0 reduced the length of the ApiKey.key field to 128. (SHA: 1cdf2c4)
This change is in `models.py`, but the migration for this change is missing

**Comment by georgedorn** [comment]
This change happened before django had a built-in migration framework.  Later, when django added one, the migrations were regenerated from scratch, so the 128-character limit is now in the initial migration creating that table: https://github.com/django-tastypie/django-tastypie/blob/master/tastypie/migrations/0001_initial.py

This won't affect many users, just those who are updating a South-era django site to a modern one, and they're going to face a ton of other migration issues.

**Comment by georgedorn** [comment]
This essentially can't be fixed inside Tastypie; if you find yourself in this situation, you're going to need to write a custom migration to get from whatever version you started on to the current one.
