### ISSUE TITLE
Overriding convert method for field

### ISSUE THREAD

**Issue by blackwood** [django-tastypie/django-tastypie#1592]
Using `django-money`, I get a `TypeError` when tastypie attempts to convert `Money` to `Decimal`. Is there a recommended way to override the convert method here so that I can use the builtin formatters provided by the field?

**Comment by georgedorn** [comment]
Can you include your resource definition and the traceback?  It might just be a configuration issue.

That said, if it's a case tastypie's built-in fields can't already handle, you can subclass APIField yourself
and implement the `convert()` method.  Then in your resource definition, use your new field class for that model field.

See https://github.com/django-tastypie/django-tastypie/blob/master/tastypie/fields.py#L272 for how the `DecimalField` is implemented currently.  Most fields just need a couple attributes and the `convert()` method defined.

**Comment by blackwood** [comment]
Hey thanks for your quick response, I actually switched to django-rest-api so I can't easily reproduce the issue. I'll close.
