### ISSUE TITLE
Supported Django versions clarification

### ISSUE THREAD

**Issue by jameswettenhall** [django-tastypie/django-tastypie#1599]
Hi @georgedorn and others,

The master branch's README.rst currently indicates support for:

"Django - 1.11 (LTS), 2.0 (LTS) or 2.1".

Given that Django v2.0 is not a Long Term Support (LTS) release, I think the "(LTS)" should be removed from after "2.0".

Also, given that the Django 2.2 pull request has been merged into master: https://github.com/django-tastypie/django-tastypie/pull/1588, will the master branch's README.rst be updated to say that Django 2.2 (LTS) is supported?

**Comment by georgedorn** [comment]
Updated in v0.14.3
