### ISSUE TITLE
Investigate relocating to gitlab and gitlab-ci.

### ISSUE THREAD

**Issue by georgedorn** [django-tastypie/django-tastypie#1606]
Travis has been increasingly painful to use for the last couple years, and I'd like to see what hosting the primary repo on gitlab would look like (which would get us gitlab-ci for almost no work).

If builds are easier to manage there, move the various pointers to the github repo to point at gitlab.  Off the top of my head, that's:  pypi, djangopackages, readthedocs.  Probably others.  Retain the github repo but add a note that it's a mirror and disable creating new issues/prs.

**Comment by mandarvaze** [comment]
For a project I was working sometime ago, we switched from Travis to CircleCI 
It is [free](https://circleci.com/open-source/) for open source projects.

**Comment by airtonix** [comment]
why?

just use github actions. or circle ci.

any amount of change will require work.

I love tastypie in comparison to drf, so don't take this the wrong way... tastypie is already an non visible project. moving to gitlab will further reduce your exposure to the community.

**Comment by mandarvaze** [comment]
> moving to gitlab will further reduce your exposure to the community.

This can be managed by having repo on both github and gitlab.
The main development could be on gitlab, if you want.
github would be just for "visibility" and is auto-synced via some automation.

**Comment by georgedorn** [comment]
Moved to github actions for now, as it was the least effort.
