### ISSUE TITLE
Remove use of deprecated django.conf.urls.urls()

### ISSUE THREAD

**Issue by swchoi727** [django-tastypie/django-tastypie#1616]
* Replace with django.urls.re_path()

**Comment by pg1671** [comment]
Now that django 4.0 is out will this be fixed? Seems like a trivial change. Or is this project dead?

**Comment by andyreagan** [comment]
Is there anyone watching for this?

**Comment by georgedorn** [comment]
> Now that django 4.0 is out will this be fixed? Seems like a trivial change. Or is this project dead?

It was not, in fact, a trivial change: https://github.com/django-tastypie/django-tastypie/pull/1632/files

Fixed in master, release to follow.

**Comment by andyreagan** [comment]
Not trivial, but still mostly find-replace.

Cheers for getting it done, regardless. I'd buy you a coffee if you have a page: https://www.buymeacoffee.com/

**Comment by pg1671** [comment]
thanks @georgedorn. Appreciate the fix.
