### ISSUE TITLE
use unittest.mock instead of mock

### ISSUE THREAD

**Issue by pgajdos** [django-tastypie/django-tastypie#1635]
Could you please consider to use built-in unittest.mock instead of mock, as a fallback at least?

https://trello.com/c/S6eADbii/64-remove-python-mock
https://fedoraproject.org/wiki/Changes/DeprecatePythonMock

**Comment by ryanneilyoung** [comment]
I've done the work in this PR: https://github.com/django-tastypie/django-tastypie/pull/1636

**Comment by georgedorn** [comment]
Done quite a while ago and definitely released in v0.14.5.
