### ISSUE TITLE
Minor issue: resources.Resource.deserialize ignores format param

### ISSUE THREAD

**Issue by vmihailenco** [django-tastypie/django-tastypie#164]
Noticed browsing the code:

    def deserialize(self, request, data, format='application/json'):
        """
        Given a request, data and a format, deserializes the given data.
        It relies on the request properly sending a ``CONTENT_TYPE`` header,
        falling back to ``application/json`` if not provided.
        Mostly a hook, this uses the ``Serializer`` from ``Resource._meta``.
        """
        deserialized = self._meta.serializer.deserialize(data, format=request.META.get('CONTENT_TYPE', 'application/json'))
        return deserialized

**Comment by SeanHayes** [comment]
This has been fixed.
