### ISSUE TITLE
Tag for v0.14.5

### ISSUE THREAD

**Issue by jayvdb** [django-tastypie/django-tastypie#1646]
https://pypi.org/project/django-tastypie/ now has v0.14.5

https://github.com/django-tastypie/django-tastypie/tags latest is [v0.14.4](https://github.com/django-tastypie/django-tastypie/releases/tag/v0.14.4)

https://build.opensuse.org/package/show/devel:languages:python:django/python-django-tastypie depends on the github release in order to have tests included.

**Comment by georgedorn** [comment]
I've created the release/tag, though nothing downstream appears to have budged.  I am unclear why, but I don't control anything outside of github, so if it doesn't produce a build you'll have to file with them.

**Comment by jayvdb** [comment]
I am the maintainer there, so now I can do my part.  Thank you.

**Comment by jayvdb** [comment]
Done
