### ISSUE TITLE
MultiAuthentication with SessionAuthentication exception when there is no CSRF token

### ISSUE THREAD

**Issue by FrancoisDupayrat** [django-tastypie/django-tastypie#1651]
Hello, after updating to:
- Django==4.1.7
- django-tastypie==0.14.5

There is an exception being thrown and not intercepted when trying to use a `MultiAuthentication` with `SessionAuthentication` and another authentication, for example `ApiKeyAuthentication`.

When trying to send a request with no CSRF token in Cookies (because other authentication methods do not require a CSRF token), an `InvalidTokenFormat` exception is raised in `django/middleware/csrf.py` method `_check_token_format`. That exception should be catched in `tastypie/authentication.py` line 315 `csrf_token = check_token_format(csrf_token)` but is not.

As a result, it's impossible to authenticate with another authentication.

The last commit to change that is this one: https://github.com/django-tastypie/django-tastypie/commit/ee87690321dffc6a192227b1b3b2c62e0e18dc51

**Comment by FrancoisDupayrat** [comment]
PR opened with an additional test that fails without the fix, and a tentative fix. All "core" tests pass with that change.

**Comment by SamkeetJain** [comment]
Can this issue be fixed?

**Comment by georgedorn** [comment]
> Can this issue be fixed?

Fixed in v0.14.6; it should have gone out sooner but I was having an issue getting RTD to notice new builds.  Fortunately that logjam appears to be resolved, at least for now.
