### ISSUE TITLE
support for python-dateutil 2.8.2

### ISSUE THREAD

**Issue by enmanuelmartinez** [django-tastypie/django-tastypie#1657]
cant install pandas 2.0.0
pandas==2.0.0 and python-dateutil==2.8.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested python-dateutil==2.8.1
    django-tastypie 0.14.4 depends on python-dateutil!=2.0 and >=1.5
    faker 4.1.3 depends on python-dateutil>=2.4
    pandas 2.0.0 depends on python-dateutil>=2.8.2

**Comment by georgedorn** [comment]
A fresh install here gives me python-dateutil==2.8.2, which is 
compatible with both tastypie and pandas.  Perhaps you have 
python-dateutil pinned in a project requirements.txt, or if you are 
managing the environment manually you'll need to upgrade it with `pip 
install -U python-dateutil`.

**Comment by enmanuelmartinez** [comment]
its done, thank you.
