### ISSUE TITLE
Feature: Optional regex filtering

### ISSUE THREAD

**Issue by derks** [django-tastypie/django-tastypie#203]
Would be handy to optionally allow regex filtering.  For example:

<pre>
/api/v1/distros/?format=json&regex=fedora

-> fedora12
-> fedora13
-> fedora14
-> fedora15
</pre>

Not sure how to implement this... and it is obviously expensive so you wouldn't want it done unless 'regex' was passed as a param.  Was thinking you could have a "regex_fields = ['field1', 'field2']"  in the Resource/ModelResource meta class ... meaning if regex is passed, only those fields are searched for the regex.

**Comment by SeanHayes** [comment]
I think this is already supported by Django: https://docs.djangoproject.com/en/1.9/ref/models/querysets/#regex
