### ISSUE TITLE
Multi-DB: Cannot specify which DB to use for created objects

### ISSUE THREAD

**Issue by remoun** [django-tastypie/django-tastypie#207]
There's no (clean) way to hook into the obj.save() step while hydrating a new object (obj_create and the new related/m2m objects with it).

I can't think of a great way to do it, but perhaps add an extension point for this kinda thing?

In the meantime, I hooked into hydrate and checking the object's private state, along the lines of:

```
def hydrate(self, bundle):
    bundle = super(SomeModelResource, self).hydrate(bundle)
    if not bundle.obj._state.db:
        bundle.obj._state.db = get_alias(bundle)
    return bundle
```

This is probably quite brittle, but it's not a great idea to mess with object internals, anyway.

**Comment by SeanHayes** [comment]
This seems fairly uncommon and there are already several workarounds:

1. Override hdyrate like you've done, and which is a perfectly fine place to modify objects.
2. Override the save method on your model
3. Configure your Django DB Routers

I was also planning on adding a `get_save_kwargs` hook method which might help with this.
