### ISSUE TITLE
Make resource_uri determining field configurable on ModelResources

### ISSUE THREAD

**Issue by eykd** [django-tastypie/django-tastypie#225]
Presently, a ModelResource's `resource_uri` field is hard-coded to the primary key. So, while there is a facility to [use non-PK data for a resource's URLs][1], the `resource_uri` field will always use the PK. This is not always desirable. The only way to change this is to override the entire `ModelResource.get_resource_uri` method, changing the string `'pk'` to the desired field. This should instead be configurable in a ModelResource's Meta options.

[1]: http://django-tastypie.readthedocs.org/en/latest/cookbook.html#using-non-pk-data-for-your-urls

Something like this:

    def get_resource_uri(self, bundle_or_obj):
        """
        Handles generating a resource URI for a single resource.
        
        Uses the model's ``username`` in order to create the URI.
        """
        kwargs = {
            'resource_name': self._meta.resource_name,
        }
        fieldname = self._meta.resource_uri_fieldname

        if isinstance(bundle_or_obj, Bundle):
            kwargs[fieldname] = getattr(bundle_or_obj.obj, fieldname)
        else:
            kwargs[fieldname] = getattr(bundle_or_obj, fieldname if fieldname != 'pk' else 'id') 
        
        if self._meta.api_name is not None:
            kwargs['api_name'] = self._meta.api_name
        
        return self._build_reverse_url("api_dispatch_detail", kwargs=kwargs)

**Comment by SeanHayes** [comment]
Fixed in 1367d7a45587b2af9969d16c3c641a255a8d5b8e
