### ISSUE TITLE
Generated resource URI always empty

### ISSUE THREAD

**Issue by dguaraglia** [django-tastypie/django-tastypie#24]
For some reason the resource URI for all of my resources seems to come up empty.

**Comment by RoboSloNE** [comment]
Hi, I have the same issue (empty "resource_uri"), but @dguaraglia 's paste is deleted now and I have no idea what was the problem there and if I have the same one.

I've mostly copy-pasted stuff from docs, so myapp/urls look somewhat like this:
```python
...
from tastypie.api import Api
from myapp.api.resources import ProjectResource

...
v1_api = Api(api_name='v1')
v1_api.register(ProjectResource())

urlpatterns = [
    ...
    url(r'^api/', include(v1_api.urls))
]
```

myapp/api/resources:
```python
...
from myapp import Project

...
class ProjectResource(ModelResource):
    class Meta:
        queryset = Project.objects.all()
        name = 'project'
```

And the model:
```python
class Project(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name
```

But API response looks like this:
```json
{
"id": 1,
"name": "TEST",
"resource_uri": ""
}
```

**Comment by stodge** [comment]
I have the same problem but I'm not using namespaces for my URLs.
