### ISSUE TITLE
In ApiField hydrate/dehydrate, using getattr() on a OneToOneField can raise a DoesNotExistException

### ISSUE THREAD

**Issue by jstlaurent** [django-tastypie/django-tastypie#260]
I ran into this issue today. The way the *hydrate* and *dehydrate* methods in ApiField use *getattr()* can result in a DoesNotExist exception being raised rather than None being returned when the attribute being "get" is a non-existent OneToOneField. 

As far as I can tell, since OneToOneField eschews the related manager and tries to return the related object directly, it executes a query that finds no result and thus raises the exception.

Specifically here:

```python
if self.blank:
     return None
elif self.attribute and getattr(bundle.obj, self.attribute, None):
     return getattr(bundle.obj, self.attribute)
elif self.instance_name and hasattr(bundle.obj, self.instance_name):
     return getattr(bundle.obj, self.instance_name)
```
and here:

```python
for attr in attrs:
    previous_object = current_object
    current_object = getattr(current_object, attr, None)
```

My solution was to replace the direct use of *getattr()* with checking first with *hasattr()*. *hasattr()* will return False without raising an exception if there is no related object. I've made a fix in my fork. I'll send a pull request, if it's alright.

**Comment by SeanHayes** [comment]
I believe this has been fixed.
