### ISSUE TITLE
loaddata / dumpdata don't see to work right

### ISSUE THREAD

**Issue by blite** [django-tastypie/django-tastypie#358]
running loaddata I get IntegrityError: Could not load tastypie.ApiKey(pk=10): column user_id is not uniq

if I exclude the tasty pie table (fine for testing)

./manage.py dumpdata --natural --indent=4 --exclude contenttypes  --exclude auth.Permission --exclude tastypie

I can restore with load data just fine.  However the actual issue is with the signal not determining whether the raw parameter is true.  

Here's how I would fix it
https://github.com/toastdriven/django-tastypie/pull/357

**Comment by SeanHayes** [comment]
Closed by #1433
