### ISSUE TITLE
Improving unacceptable performance?

### ISSUE THREAD

**Issue by nisc** [django-tastypie/django-tastypie#371]
Hello,

are there any strategies to increase the performance of a TastyPie API? I'm experiencing bad performance (factor 15 compared to a similar API implemented in a faster language) and wonder if I can do anything about it.

A few facts:
Main resource: 3 `TextField`s, 4 `ToOneField`s, 3 `ToManyField`s. (The referenced resources don't have any other outside relations themselves.)
Database: SQLite
(De-)Serializer: JSON

What's the problem:
If I query the main resource with ?limit=600, the CPU is busy for about 9 seconds (2GHz). 

What I have tried:
1) Removing `full=True` (resource inlining) from the fields in my main resource does not help much.
2) Removing the relations to the foreign resources from the main resource does help a lot (e.g., removing some of the  `ToOneField`s), but obviously this is not an option.
3) Enabling the `SimpleCache` and configuring the `CACHES` in `settings.py` did not seem to help at all. How would I confirm that it's actually doing anything?
4) Using the XML (de-)serializer instead of JSON adds 3 additional seconds.
5) `DEBUG=True` only accounts for about 500ms.

What I'm thinking about:
1) Merging my models and reducing the number of resources.
2) Node.js?? Java??

Any ideas?

**Comment by SeanHayes** [comment]
Closing in favor of #1372
