### ISSUE TITLE
HTTP 500 if json payload has a redundant comma

### ISSUE THREAD

**Issue by sharang** [django-tastypie/django-tastypie#431]
when I POST a json payload like {"key": "value",}
I get a HTTP 500.

If I remove the last comma, just POST {"key": "value"}
everything goes well.

{"error_message": "Expecting property name: line 1 column 16 (char 16)", "traceback": "Traceback (most recent call last):

  File \"build/bdist.linux-x86_64/egg/tastypie/resources.py\", line 195, in wrapper
    response = callback(request, *args, **kwargs)

  File \"build/bdist.linux-x86_64/egg/tastypie/resources.py\", line 402, in dispatch_list
    return self.dispatch('list', request, **kwargs)

  File \"build/bdist.linux-x86_64/egg/tastypie/resources.py\", line 431, in dispatch
    response = method(request, **kwargs)

  File \"build/bdist.linux-x86_64/egg/tastypie/resources.py\", line 1176, in post_list
    deserialized = self.deserialize(request, request.raw_post_data, format=request.META.get('CONTENT_TYPE', 'application/json'))

  File \"build/bdist.linux-x86_64/egg/tastypie/resources.py\", line 351, in deserialize
    deserialized = self._meta.serializer.deserialize(data, format=request.META.get('CONTENT_TYPE', 'application/json'))

  File \"build/bdist.linux-x86_64/egg/tastypie/serializers.py\", line 194, in deserialize
    deserialized = getattr(self, \"from_%s\" % desired_format)(content)

  File \"build/bdist.linux-x86_64/egg/tastypie/serializers.py\", line 344, in from_json
    return simplejson.loads(content)

  File \"/usr/local/lib/python2.7/json/__init__.py\", line 326, in loads
    return _default_decoder.decode(s)

  File \"/usr/local/lib/python2.7/json/decoder.py\", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File \"/usr/local/lib/python2.7/json/decoder.py\", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)

ValueError: Expecting property name: line 1 column 16 (char 16)
"}

**Comment by SeanHayes** [comment]
Duplicated by #1053, fixed in e9048fd8f47994840b69dc73ac44170c351a1114
