### ISSUE TITLE
Saving FKs breaks Authorization

### ISSUE THREAD

**Issue by achur** [django-tastypie/django-tastypie#480]
At https://github.com/toastdriven/django-tastypie/blob/master/tastypie/resources.py#L1857, tastypie calls `save_related` "just in case".  This causes problems with reasonable Authorization behavior, as it is impossible for a validly created resource to have a read-only resource as a foreign key.

For more specificity, the bug appears in the following situation:

I have:

 - A __Note__ resource representing a note left by a user.  Only the user who created a Note can edit it. 
 - A __Comment__ resource.  Comments can be left on any note by any user.

__TL;DR:__ I am unable to limit Note editing to a Note's creator while still allowing any user to comment on a Note.

I am using the following setup for Authentication:

    class CreatedByEditAuthorization(Authorization):
        def is_authorized(self, request, object=None, **kwargs):
            return True
    
        def apply_limits(self, request, object_list):
            if request and request.method != 'GET' and hasattr(request, 'user'):
                return object_list.filter(created_by=request.user)
            return object_list

In short, a user is only authorized to edit objects for which they are equal to the created_by property (they can only edit the objects they created).

This is linked as follows:

    class NoteResource(ModelResource):
        comments = fields.ToManyField('myapp.api.resources.CommentResource', 'comments', null=True, blank=True)
        created_by = fields.ToOneField('account.api.resources.UserResource', 'created_by')
    
        # Attach the user on creation
        def obj_create(self, bundle, request, **kwargs):
            return super(NoteResource, self).obj_create(bundle, request, created_by=request.user)
    
        class Meta:
            queryset = Note.objects.all()
            allowed_methods = ['get', 'put', 'post']
            authorization = CreatedByEditAuthorization()

so here, when an object is created, I automatically attach the current user to the `created_by` attribute and link it to the proper Authorization.

A `Comment` resource is simple and just has a `ForeignKey` to a `Note` resource.

__The problem is this:__  if user A creates a Note and user B attempts to create a comment with that Note as a Foreign Key, tastypie does an update (by calling `save_related`) on that Note.  That attempt is rejected as user B did not create the Note, so it doesn't pass Authorization.

__There are two potential solutions:__

- Provide a way to tell a `Resource` not to `save_related` on a given ForeignKey
- Pass along additional information to the Authorization so it knows if `is_authorized` was requested as a result of `save_related`.

**Comment by SeanHayes** [comment]
This should be fixed by #456
