### ISSUE TITLE
Default hydrate implementation in ApiField is buggy

### ISSUE THREAD

**Issue by mitar** [django-tastypie/django-tastypie#491]
Currently, there is such code:

```
elif self.attribute and getattr(bundle.obj, self.attribute, None):
    return getattr(bundle.obj, self.attribute)
elif self.instance_name and hasattr(bundle.obj, self.instance_name):
    return getattr(bundle.obj, self.instance_name)
```

It should probably be changed to:

```
elif self.attribute and getattr(bundle.obj, self.attribute, None) is None:
    return getattr(bundle.obj, self.attribute)
elif self.instance_name and getattr(bundle.obj, self.instance_name, None) is None:
    return getattr(bundle.obj, self.instance_name)
```

because what if value is `False`? Or `{}`? Or `[]`? The first if is not run for them. While the second is run even if the value is `None` (which is then returned as a proper value even if `null` is set to `False`).

So default should ApiField check only for `None` and throw an exception if it is `None` and `null` is not set. It could be argued that for `DictField` or `ListField` also `{}` or `[]` should be seen as null value, but this is probably some other ticket.

**Comment by SeanHayes** [comment]
I think this was fixed a while ago.
