### ISSUE TITLE
Patch method on resource with toOneField(full = True) fails.

### ISSUE THREAD

**Issue by phonkee** [django-tastypie/django-tastypie#501]
Resource with 
    order = fields.ToOneField('pohoda.api.resources.OrderResource', 'order', full = True)

when I try to update (PATCH) integer field on resource i got this error:
The 'order' field has was given data that was not a URI, not a dictionary-alike and does not have a 'pk' attribute:

when I set full = False it works.
But I think a lot of people do not want to perform N other http requests..

**Comment by SeanHayes** [comment]
Seems to be fixed, closing.
