### ISSUE TITLE
Hydration of Missing and Null Values

### ISSUE THREAD

**Issue by joshbohde** [django-tastypie/django-tastypie#518]
Hydration of fields with missing or null values has a lot of corner cases that cause issues. A fix for one would probably fix all of them. Opening this to keep for documenting these issues and discussion.

See also:

   * #492 (Cannot PUT `None` to a previously non-`None` value)
   * #496 (PUT of `{}` succeeds)
   * #491 (Falsy existing values are handled as if there is no existing value)
   * #271 (Defaults return before None when both are valid)
   * #501 (PATCHes not containing existing fields can fail)

**Comment by lsapan** [comment]
Obviously this is an old issue, but it's worth mentioning that this no longer seems to be an issue.

**Comment by SeanHayes** [comment]
Most of the related issues have been fixed, the rest have been added to milestones. Closing. Thanks for reporting!
