### ISSUE TITLE
POST to reverse one to one relation does not save properly

### ISSUE THREAD

**Issue by dhatch** [django-tastypie/django-tastypie#566]
When posting to the reverse side of a one to one relation, the post does not complete properly.  

I've added a (currently failing) test case for this at 58598f5934cb7e5d051e74320aaa36295dc6b0a7.  The issue seems to lie in django's saving of reverse one to one relations.  It does not occur properly, I've opened a ticket at https://code.djangoproject.com/ticket/18638 where you can read more and see a failing test case in the django code base attached as a patch.  

As a workaround, it would be possible to set the `related_name` property on ToOneFields via introspection of the associated django field.  The saving process which occurs in `ModelResource.save_related` when the `related_name` property exists would properly save the one to one relation (as it then saves using the forward one to one relationship).

**Comment by SeanHayes** [comment]
I think this was fixed in #1378.
