### ISSUE TITLE
Django DateField is assigned as DateTimeField

### ISSUE THREAD

**Issue by akoumjian** [django-tastypie/django-tastypie#591]
https://github.com/toastdriven/django-tastypie/blob/master/tastypie/resources.py#L1553

When the ModelResource fields are created, this sets the DateField type to a tastypie DateTimeField. This causes it to be improperly handled in some instances and can break form validation when used with the model.

**Comment by nutztherookie** [comment]
is there a solution to this problem?

**Comment by SeanHayes** [comment]
Fixed in b248e7fda8c029bf0309b5e1f0e9db99328d5642
