### ISSUE TITLE
PUT returns 204 even if I provide non-existant fields

### ISSUE THREAD

**Issue by ondrowan** [django-tastypie/django-tastypie#596]
If I try to PUT a resource with additional (non-existant) field, it PUTs all changed data as usual and ignores this additional field. Additionally if I provide only part of fields, it acts as if I used PATCH and updates only provided fields. Is this behaviour correct? It seems to me as if PUT and PATCH were mixed up at the moment.

**Comment by SeanHayes** [comment]
Closing in favor of #601
