### ISSUE TITLE
Please make the usage more simple and straightforward

### ISSUE THREAD

**Issue by dekoza** [django-tastypie/django-tastypie#599]
Tastypie is quite appealing but as I see from the docs, lots of things break the DRY principle. For example if I just want to provide RESTful access to the database (expose most of the Models), Tastypie requires me to write a small Resource for every model and register it separately. And the only thing that changes is the name of the Model. Then if some of my Models have a Foreign Key to other Models I need to set an extra field in the Resource for each relation to handle them. The rationale is that "Tastypie doesn't know how you want to represent the data". But I just want a ForeignKey relation (as in Tutorial). Then if I want to change the default Authentication/Authorisation, I have to change it in every Resource. And then, like a cherry on a pie, comes this strange thing of passing instances of classes to register() instead of passing just classes.

So the idea is to "slightly" refactor the behavior of Tastypie so it would be more like Django Admin to work with:
* The most basic thing should be to register a Model subclass to the API and Tastypie should produce a Resource on its basis. If you pass list of classes - they all should get some basic ModelResource created behind the scenes. It would be the same logic as in Django Admin when you register your Models and you can instantly play with the Admin, then you start to fiddle with the Admin by creating and registering individual ModelAdmins. I'm all for the same logic in Tastypie. Besides, the name of the resource should be computed from the name of the Model subclass and the basic queryset should be <Model>.objects.all() since it's the first thing you'd do to test if your API works. And you should register classes not instances - an instance should be created behind the scene.
* One should be able to set Authorization and Authentication backends globally and they should be overridden on a per-resource basis.
* Default ModelResource should introspect relations in the most straightforward way possible
* Self-designed Resources should be as decoupled from Models as possible so they could be reused on similar Models
* When registering Resource we should be able to provide a Validation subclass or even simpler - a Form subclass to validate against - that will be used if a Resource is PUT via our API.

In other words, using Tastypie should be as easy as:
```python
from tastypie.api import Api
from tastypie.authentication import ApiKeyAuthentication, Authentication
from tastypie.authorization import DjangoAuthorization, ReadOnlyAuthorization
from tastypie.resources import ModelResource, Resource
from myblogapp.models import Entry, Category, Comment
from myblogapp.forms import CommentForm

v1 = Api(api_name='v1', authentication=Authentication, authorisation=ReadOnlyAuthorization)
   
class CommentResource(ModelResource):
    class Meta:
        filters = {'approved' : True} # instead of queryset = Comment.objects.filter(approved=True)
        authentication = ApiKeyAuthentication
        authorisation = DjangoAuthorization


class SearchResource(Resource):
    # here goes the magic with Haystack
    class Meta:
        resource_name = 'search'


v1.register([Entry, Category])  # ModelResource tailored behind the scene for each Model in the list
v1.register(Comment, CommentResource, CommentForm)  # all Resource logic is based on Comment, extra options taken from ModelResource subclass and CommentForm will be used to validate the data
v1.register(SearchResource)  # it can be alone as it's not a subclass of ModelResource; this should auto-distinct between Model, Resource and ModelResource
```

What do you think?

**Comment by SeanHayes** [comment]
From #634: "I'm not sure this is worth the complication to our tests.

It's pretty easy to create a resource already, and letting users create a resource merely by specifying a model class seems like it could lead to security issues."

We'll add some cookbook examples for increasing code reuse though: #1367

**Comment by SeanHayes** [comment]
#1092 may be of interest
