### ISSUE TITLE
api_name in _meta is lost

### ISSUE THREAD

**Issue by vvolodin** [django-tastypie/django-tastypie#612]
api_name in _meta is lost in a second level relationship causing failure to generate reverse url

**Comment by darlanalves** [comment]
@joshbohde Exactly! 

Just came across the same error and it was the same symptom, except in my case the resource name was a string, like "app.apy.Name", when it should be "app.apy.NameResource".

**Comment by SeanHayes** [comment]
Closing due to age and lack of unittest/confirmation.
