### ISSUE TITLE
prepend_urls bypasses authentication

### ISSUE THREAD

**Issue by Roarster** [django-tastypie/django-tastypie#641]
Apologies if what I'm doing here is by design or if I'm just doing things completely wrong but I think using prepend_urls to create a nested resource bypasses the authentication on both the parent and child resource.  I've created an example similar to that in the Cookbook and have created a child resource using ApiKey authentication and I'm able to access that despite not passing the correct headers.  The parent resource also requires ApiKey authentication.

What I see without authentications headers is:

GET /api/v1/article - 401 as expected
GET /api/v1/article/1/ - 401 as expected
GET /api/v1/article/1/tags - The list of tags is unexpectedly returned.

It seems to me this is incorrect and certainly isn't what I would expect to see.

**Comment by smesdaghi** [comment]
This is an old thread but since the issues is still open and ranked high in my search... a call to 
```self.is_authenticated(request)``` in the fist line of the handler will take care of the issue. tested with tastypie 0.11 & 0.12.

**Comment by SeanHayes** [comment]
The cookbook now recommends using self.wrap_view() inside prepend_urls(), closing this issue.

**Comment by servomac** [comment]
Event with wrap_view, I needed `self.is_authenticated(request)` in the handler method.
