### ISSUE TITLE
Cookbook example busted

### ISSUE THREAD

**Issue by toastdriven** [django-tastypie/django-tastypie#65]
From Wojtek:

http://toastdriven.github.com/django-tastypie/cookbook.html

it wasn't obvious what happens/should happen with the user that's fetched from the db in dispatch(), I assumed it was going to be included in an orm filter but giving it a quick test it turns out it wasn't, at least not when getting a list of items. A quick change to "obj_get_list", such as adding:

applicable_filters.update(kwargs)

seems to get the job done.

**Comment by georgedorn** [comment]
I'm reasonably sure this refers to an obsolete recipe.  While I'm not positive the new recipe is correct (there may be an issue about that elsewhere) this is probably closable.
