### ISSUE TITLE
Complex Authorization

### ISSUE THREAD

**Issue by hughes** [django-tastypie/django-tastypie#709]
For a current project, with many dozens of resources, I need to be able to `&` and `|` Authorization methods together in order to re-use smaller, modular Authorization types. Similar to how django querysets allow complex lookups using `Q` objects.

My goal is to be able to do something like this:

    authorzation = (FooAuthorization() | BarAuthorization()) & BazAuthorization()

In the above example, `is_authorized` would return `True` if (Foo OR Bar) AND Baz are authorized. 

`apply_limits` would probably work by extending the `object_list` when using `|` and by intersecting when using `&`

I've drafted out a couple ideas and it doesn't seem like it would be too difficult to do.

Do you think this would be a useful addition to the project once I'm finished?

**Comment by SeanHayes** [comment]
Can't find the related branch, and the suggested changes are for an outdated version of tastypie. Also, this seems like it would add a lot of unnecessary complexity.

**Comment by hughes** [comment]
Yeah this was super old, super complicated and ended up being the wrong approach. I should have killed this PR years ago!

**Comment by SeanHayes** [comment]
NP. I've just been organizing various issues and PRs as I come across them.
