### ISSUE TITLE
Hydration of many (5000) resources very slow due to deepcopy in Resource.__init__()

### ISSUE THREAD

**Issue by katzj** [django-tastypie/django-tastypie#720]
I'm doing some profiling to speed up an API that I'm building with tastypie and am seeing ~ 70% (5 of 7 seconds) of my time being spent right now doing the deepcopy of the base fields in Resource.__init__ when hydrating 5000 resources.  

Given the general nature of the Resource object, I guess there are probably cases where you'd have a mutable object in the base Resource and need to create new ones for each instance but is that also true for ModelResources?

**Comment by SeanHayes** [comment]
This has been fixed using @tolomea's snippet. Thanks for reporting!
