### ISSUE TITLE
0.9.12: class Resource no longer validates for put_list, put_detail, post_list, patch_list

### ISSUE THREAD

**Issue by kojustin** [django-tastypie/django-tastypie#737]
When POSTing to a resource, my custom validation no longer runs. 

At HEAD of tastypie master (eee008f3eef0f756b32635e7b74c1c9732cf593c), the Resource class doesn't run any validations, even if one of specified in the META class. This differs from 0.9.11. The commit that made this change was c5451b9. That commit removed the "self.is_valid()" calls to put_list(), put_detail(), post_list(), patch_list().

**Comment by maxsmythe** [comment]
Another problem with moving the validation class to the save() method:

When the validator cleans data, potentially changing it (a valid use case according to django and tastypie docs), those modifications are not respected, as the object members are actually populated in the obj_create() method, before is_valid is run.

**Comment by kojustin** [comment]
Closing, this is against a version of tastypie that is three years old, this is never going to be fixed.
