### ISSUE TITLE
GenericResource doesn't pass request in get_via_uri

### ISSUE THREAD

**Issue by slurms** [django-tastypie/django-tastypie#739]
Using a `GenericForeignKeyField` in a `ModelResource` with a custom `Authorization` class that filters the object list in apply_limits results in an `AttributeError` when accessing attributes on request. This is caused by `get_via_uri` not passing the request object to `obj_get`.

**Comment by SeanHayes** [comment]
A `Bundle` is passed to `obj_get()`, which contains the `request`.
