### ISSUE TITLE
Allow Meta.fields to be empty list to specify no field introspection

### ISSUE THREAD

**Issue by warvariuc** [django-tastypie/django-tastypie#793]
> fields
Controls what introspected fields the Resource should include. A whitelist of fields. Default is []

Please mention that if Meta.fields == [] it means that ALL Django model fields are introspected. To simulate no introspection you can do `Meta.fields = ['']`
http://stackoverflow.com/questions/14597332/tastypie-custom-fields

**Comment by SeanHayes** [comment]
I'll update the code to support `Meta.fields = None`, since it's cleaner.

**Comment by SeanHayes** [comment]
Actually, tastypie should probably obey when a user explicitly provides an empty list.
