### ISSUE TITLE
Support ActiveModel::Serializers style side loading of data

### ISSUE THREAD

**Issue by go1dfish** [django-tastypie/django-tastypie#820]
https://github.com/rails-api/active_model_serializers

ActiveModel::Serializers for rails allows resources to return a list of related ids per item and then a full list of all unique resources in a separate array on the side.

This is beneficial when dealing with large data sets containing overlapping relationships without duplicating the data returned in embedded objects.

**Comment by SeanHayes** [comment]
It would be nice, but I think it would change tastypie's design too much.

There are projects out there that let you batch execute multiple requests to Django in a single request, you could execute several GETs at once on resources that return resource_uris instead of full related resources.
