### ISSUE TITLE
Please update django-tastypie.readthedocs.org and tastypieapi.org

### ISSUE THREAD

**Issue by ivanvotti** [django-tastypie/django-tastypie#837]
Documentation on [django-tastypie.readthedocs.org](https://django-tastypie.readthedocs.org) doesn't look consistent with the last version of tastypie.

For example [cookbook page](https://django-tastypie.readthedocs.org/en/latest/cookbook.html) still says: "This could be done by applying a filter in the `apply_authorization_limits` method of your resource."

But `apply_authorization_limits` has been completely deprecated (#809)

Documentation link on [http://tastypieapi.org/](http://tastypieapi.org/) is not correct. And current stable version is 0.9.12

**Comment by SeanHayes** [comment]
Closed by #1433
