### ISSUE TITLE
Tastypie returns a list of cached objects to unauthenticated users

### ISSUE THREAD

**Issue by erikcw** [django-tastypie/django-tastypie#882]
This issue is in the context of a locked down Resource with Authentication/Authorization set to require a logged in user for GET requests.

If a project is using the Django caching middleware, tastypie will return cached results (and status_code 200) to unauthenticated users instead of a 401 error.

The work around is setting `CACHE_MIDDLEWARE_ANONYMOUS_ONLY = True`

I'm not sure if this is possible to fix, since the caching middleware probably returns the response before the request ever hits tastypie.  It should however be documented.

**Comment by laurafeier** [comment]
If you're using <code>BasicAuthentication</code>(or other authentication types based on the <code>HTTP_AUTHORIZATION</code> header) adding <code>cache = NoCache(varies=["Accept", "Authorization"])</code> to your Resource's Meta options might fix this for you.

**Comment by ahammouda3** [comment]
I have a potentially identical issue (Django 1.8 and tastypie version 0.13.3).  Essentially, the behavior is that my authentication middleware sets request.user to be the logged in user, while the authentication code for tastypie wraps grabs a totally different user (with the call to request.META.get('HTTP_AUTHORIZATION', '')).  Is there any way to set this up to coordinate more intuitively with the authentication middleware of Django, or is there something more fundamentally wrong with my tastypie configuration?

**Comment by SeanHayes** [comment]
@ahammouda3 You'll want to use SessionAuthentication to let Django decide if a user is authenticated.

**Comment by ahammouda3** [comment]
Thank you @SeanHayes !

**Comment by SeanHayes** [comment]
This shouldn't be an issue anymore since Django has since changed the way its caching middleware works.
