### ISSUE TITLE
Support for custom user models causes circular imports

### ISSUE THREAD

**Issue by qfel** [django-tastypie/django-tastypie#943]
https://github.com/toastdriven/django-tastypie/blob/2ebb362544bf6da3fbc6849d7a32d545bdf8e096/tastypie/authentication.py#L13

This calls get_user_model at import time, causing Django to import all apps, possibly causing circular import. Something like:

project.app1.models: from tastypie.authentication import Authentication
project.app2.models: from project.app1.models import Something

If project.app1.models is imported first, it will indirectly import project.app2.models, causing import error (because some symbols are not yet defined).

**Comment by SeanHayes** [comment]
This has been fixed.
