### ISSUE TITLE
Decimal field causing "Cannot convert float to Decimal"

### ISSUE THREAD

**Issue by phoebebright** [django-tastypie/django-tastypie#974]
Even though the field causing the problem was in this exclude list.

Easy fix in fields.py, just convert value to string first:

class DecimalField(ApiField):
    """
    A decimal field.
    """
    dehydrated_type = 'decimal'
    help_text = 'Fixed precision numeric data. Ex: 26.73'

    def convert(self, value):
        if value is None:
            return None

        return Decimal(str(value))    <----- change here.

**Comment by SeanHayes** [comment]
Fixed in #1103
