### ISSUE TITLE
ResourceOptions inherit poorly across Resources

### ISSUE THREAD

**Issue by sfllaw** [django-tastypie/django-tastypie#98]
Because ResourceOptions do not inherit from parent._meta, Resource inheritance is broken. For instance, if you have this chunk of code:

    from tastypie.resources import Resource

    class GetOnlyResource(Resource):
        class Meta:
            allowed_methods = ['get']

    class MyResource(GetOnlyResource):
        class Meta:
            pass

    print Resource._meta.allowed_methods
    print GetOnlyResource._meta.allowed_methods
    print MyResource._meta.allowed_methods

you will get the following result:

    ['get', 'post', 'put', 'delete']
    ['get']
    ['get', 'post', 'put', 'delete']  # <-- wrong!

Of course, the expected result should be just `['get']`, because MyResource is inheriting from GetOnlyResource and has not overridden `allowed_methods`.

**Comment by georgedorn** [comment]
This behaves _exactly_ like Django's model inheritance.  From the Django docs linked to:

```
 If a child class does not declare its own Meta class, it will inherit the parent’s Meta.
```

Your example child class does declare its own Meta class, even though it doesn't do anything.  I've confirmed that if you don't declare a Meta in the child class, the parent's is inherited:

```
from tastypie.resources import Resource
class GetOnlyResource(Resource):
    class Meta:
        allowed_methods = ['get']

class MyResource(GetOnlyResource):
    pass

class MyOtherResource(Resource):
    pass

In [1]: MyResource._meta.allowed_methods
Out [1]: ['get']

In [2]: MyOtherResource._meta.allowed_methods
Out[2]: [u'get', u'post', u'put', u'delete', u'patch']
```
