### ISSUE TITLE
updating the bundle.obj in hydrate doesn't stick

### ISSUE THREAD

**Issue by idbill** [django-tastypie/django-tastypie#983]
I have an model object that has a foreign key to another model object. Using hydrate, I was led to believe that I could update the bundle.obj before save. As per:
http://django-tastypie.readthedocs.org/en/latest/resources.html# (hydrate section & example)
'Broadly speaking, this takes the recently-deserialized bundle.data dictionary & builds bundle.obj (but does NOT save it).'

So my hydrate function looks like:

    def hydrate( self, bundle ):
        if 'client_id' in bundle.data.keys():
            bundle.obj.client = Client.objects.get( client_id = bundle.data['client_id'] )
        print bundle.obj.client
        return bundle

the print statement above indicates that change is made, but the save fails because the value isn't set....

**Comment by SeanHayes** [comment]
For future reference, Resource.hydrate() is called before the individual fields are hydrated, so the value might get overwritten. Overriding Resource.full_hydrate(), setting any values after you call super(), should work.
