### ISSUE TITLE
Better exception handling for Tastypie API call

### ISSUE THREAD

**Issue by gitaarik** [django-tastypie/django-tastypie#985]
When there's an exception in Tastypie and it's not a 404, then when DEBUG is True, Tastypie will show a Django error page, and when DEBUG is False, Tastypie will display an error message in JSON format and call Django's `mail_admins()` to notify the admins about the error.

While this is very nice, some exceptions are not because of a bad/incomplete implementation of your API, but because the API call that was done was bad/incomplete.

For example, when I do a POST to my API with an unsuported serialization format by having a header like for example this:

    Content-Type: unknown/unknown;

Then Tastypie will raise a `UnsupportedFormat` exception. In development we get a nice Django error page which is nice for debugging. But in production, we get an email through `mail_admins()`. This means that if you have an API that's being implemented by a lot of people that make mistakes like these, you will be spammed with errors in your email, resulting in not being able to separate the real errors from the "non" errors.

I know you can overwrite the `wrap_view()` method and do your own error handling. However, I don't think this is the most beautiful way to do it. If you overwrite this method you have to do replicate a lot of logic from the original code.

In this case I actually prefer overwriting `_handle_500()` as I describe in this Stackoverflow answer:
http://stackoverflow.com/a/17678044/1248175

However, I think the best way to do fix this is the following:

Devide the Tastypie exceptions in two categories:
- Implementation exceptions
- API call exceptions

The implementation exceptions are raised because of a bad/incomplete Tastypie class implementation (like Resources).

The API call exceptions are raised because of a bad/incomplete API call.

Then the implementation exceptions WILL do `mail_admins()` and the API call exceptions WON'T. It would also be nice if the JSON error message would contain an explanation of why the error occured.

What are your thoughts?

**Comment by SeanHayes** [comment]
Todo: In _handle_500, except UnsupportedFormat and return proper 4xx error.

**Comment by SeanHayes** [comment]
Closed in favor of #1154
