### ISSUE TITLE
Super Bulk Operations

### ISSUE THREAD

**Issue by kittles** [django-tastypie/django-tastypie#993]
I have been thinking it might be kind of handy, in order to cut down on the total number of requests, to be able to send a request (not sure which method or endpoint would make sense) with something like the following JSON:

    {
        "GET": [
            "/api/ir/batch/?format=json",
            "/api/ir/step/?format=json",
            "/api/ir/process/?format=json"
        ],
        "PATCH": [
            {
                "resource_uri": "/api/ir/step/2",
                "length": 3    
            },
            {
                "resource_uri": "/api/ir/step/2",
                "offset": 1,    
                "notes": "bulk operations could be cool!"
            }
        ],
        "PUT": [
            {
                "resource": "/api/ir/process/",
                "name": "some process",
                "size": 120,
                "start_date": "12/12/2012"
            },
            {
                "resource": "/api/ir/batch/",
                "name": "some batch",
                "description": "a batchy batch",
                "attr": "val"
            }
        ],
        "DELETE": [
            "/api/ir/batch/2",
            "/api/ir/batch/4",
            "/api/ir/batch/12",
            "/api/ir/step/9",
            "/api/ir/step/11"
        ]
    }

The response back would contain the typical responses of each individual api request in the same order. Does this seem like a useful feature or a can of worms?

**Comment by jonykalavera** [comment]
i wish i read this post earlier. :/ https://github.com/jonykalavera/django-tastypie-batch

**Comment by SeanHayes** [comment]
Cool, looks like there's a few solutions out there that can take care of this. Closing.
